/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * Customs declaration for an international export shipment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CustomsDeclarationDTO {
  /**
   * What the shipment contains, for customs
   */
  @JsonAdapter(ContentsTypeEnum.Adapter.class)
  public enum ContentsTypeEnum {
    MERCHANDISE("merchandise"),
    
    GIFT("gift"),
    
    SAMPLE("sample"),
    
    DOCUMENTS("documents");

    private String value;

    ContentsTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ContentsTypeEnum fromValue(String value) {
      for (ContentsTypeEnum b : ContentsTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ContentsTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ContentsTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ContentsTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ContentsTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ContentsTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CONTENTS_TYPE = "contentsType";
  @SerializedName(SERIALIZED_NAME_CONTENTS_TYPE)
  @javax.annotation.Nullable
  private ContentsTypeEnum contentsType;

  public static final String SERIALIZED_NAME_REASON_FOR_EXPORT = "reasonForExport";
  @SerializedName(SERIALIZED_NAME_REASON_FOR_EXPORT)
  @javax.annotation.Nullable
  private String reasonForExport;

  public static final String SERIALIZED_NAME_INCOTERM = "incoterm";
  @SerializedName(SERIALIZED_NAME_INCOTERM)
  @javax.annotation.Nullable
  private String incoterm;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nullable
  private String currency;

  public CustomsDeclarationDTO() {
  }

  public CustomsDeclarationDTO contentsType(@javax.annotation.Nullable ContentsTypeEnum contentsType) {
    this.contentsType = contentsType;
    return this;
  }

  /**
   * What the shipment contains, for customs
   * @return contentsType
   */
  @javax.annotation.Nullable
  public ContentsTypeEnum getContentsType() {
    return contentsType;
  }

  public void setContentsType(@javax.annotation.Nullable ContentsTypeEnum contentsType) {
    this.contentsType = contentsType;
  }


  public CustomsDeclarationDTO reasonForExport(@javax.annotation.Nullable String reasonForExport) {
    this.reasonForExport = reasonForExport;
    return this;
  }

  /**
   * Reason the goods are being exported
   * @return reasonForExport
   */
  @javax.annotation.Nullable
  public String getReasonForExport() {
    return reasonForExport;
  }

  public void setReasonForExport(@javax.annotation.Nullable String reasonForExport) {
    this.reasonForExport = reasonForExport;
  }


  public CustomsDeclarationDTO incoterm(@javax.annotation.Nullable String incoterm) {
    this.incoterm = incoterm;
    return this;
  }

  /**
   * Incoterm governing who pays duties/taxes
   * @return incoterm
   */
  @javax.annotation.Nullable
  public String getIncoterm() {
    return incoterm;
  }

  public void setIncoterm(@javax.annotation.Nullable String incoterm) {
    this.incoterm = incoterm;
  }


  public CustomsDeclarationDTO currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Currency of the declared item values (ISO-4217)
   * @return currency
   */
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomsDeclarationDTO customsDeclarationDTO = (CustomsDeclarationDTO) o;
    return Objects.equals(this.contentsType, customsDeclarationDTO.contentsType) &&
        Objects.equals(this.reasonForExport, customsDeclarationDTO.reasonForExport) &&
        Objects.equals(this.incoterm, customsDeclarationDTO.incoterm) &&
        Objects.equals(this.currency, customsDeclarationDTO.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentsType, reasonForExport, incoterm, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomsDeclarationDTO {\n");
    sb.append("    contentsType: ").append(toIndentedString(contentsType)).append("\n");
    sb.append("    reasonForExport: ").append(toIndentedString(reasonForExport)).append("\n");
    sb.append("    incoterm: ").append(toIndentedString(incoterm)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("contentsType");
    openapiFields.add("reasonForExport");
    openapiFields.add("incoterm");
    openapiFields.add("currency");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustomsDeclarationDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustomsDeclarationDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomsDeclarationDTO is not found in the empty JSON string", CustomsDeclarationDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustomsDeclarationDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CustomsDeclarationDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("contentsType") != null && !jsonObj.get("contentsType").isJsonNull()) && !jsonObj.get("contentsType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contentsType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contentsType").toString()));
      }
      // validate the optional field `contentsType`
      if (jsonObj.get("contentsType") != null && !jsonObj.get("contentsType").isJsonNull()) {
        ContentsTypeEnum.validateJsonElement(jsonObj.get("contentsType"));
      }
      if ((jsonObj.get("reasonForExport") != null && !jsonObj.get("reasonForExport").isJsonNull()) && !jsonObj.get("reasonForExport").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reasonForExport` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reasonForExport").toString()));
      }
      if ((jsonObj.get("incoterm") != null && !jsonObj.get("incoterm").isJsonNull()) && !jsonObj.get("incoterm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `incoterm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("incoterm").toString()));
      }
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomsDeclarationDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomsDeclarationDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomsDeclarationDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomsDeclarationDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomsDeclarationDTO>() {
           @Override
           public void write(JsonWriter out, CustomsDeclarationDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomsDeclarationDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustomsDeclarationDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustomsDeclarationDTO
   * @throws IOException if the JSON string is invalid with respect to CustomsDeclarationDTO
   */
  public static CustomsDeclarationDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomsDeclarationDTO.class);
  }

  /**
   * Convert an instance of CustomsDeclarationDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

