/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.delivery.hub.sdk.model.TimeIntervalDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * Schedule for a single day
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class DayScheduleDTO {
  public static final String SERIALIZED_NAME_CLOSED = "closed";
  @SerializedName(SERIALIZED_NAME_CLOSED)
  @javax.annotation.Nullable
  private Boolean closed;

  public static final String SERIALIZED_NAME_INTERVALS = "intervals";
  @SerializedName(SERIALIZED_NAME_INTERVALS)
  @javax.annotation.Nullable
  private List<TimeIntervalDTO> intervals = new ArrayList<>();

  public DayScheduleDTO() {
  }

  public DayScheduleDTO closed(@javax.annotation.Nullable Boolean closed) {
    this.closed = closed;
    return this;
  }

  /**
   * Whether the location is closed on this day
   * @return closed
   */
  @javax.annotation.Nullable
  public Boolean getClosed() {
    return closed;
  }

  public void setClosed(@javax.annotation.Nullable Boolean closed) {
    this.closed = closed;
  }


  public DayScheduleDTO intervals(@javax.annotation.Nullable List<TimeIntervalDTO> intervals) {
    this.intervals = intervals;
    return this;
  }

  public DayScheduleDTO addIntervalsItem(TimeIntervalDTO intervalsItem) {
    if (this.intervals == null) {
      this.intervals = new ArrayList<>();
    }
    this.intervals.add(intervalsItem);
    return this;
  }

  /**
   * Time intervals when the location is open
   * @return intervals
   */
  @javax.annotation.Nullable
  public List<TimeIntervalDTO> getIntervals() {
    return intervals;
  }

  public void setIntervals(@javax.annotation.Nullable List<TimeIntervalDTO> intervals) {
    this.intervals = intervals;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DayScheduleDTO dayScheduleDTO = (DayScheduleDTO) o;
    return Objects.equals(this.closed, dayScheduleDTO.closed) &&
        Objects.equals(this.intervals, dayScheduleDTO.intervals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(closed, intervals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DayScheduleDTO {\n");
    sb.append("    closed: ").append(toIndentedString(closed)).append("\n");
    sb.append("    intervals: ").append(toIndentedString(intervals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("closed");
    openapiFields.add("intervals");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DayScheduleDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DayScheduleDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DayScheduleDTO is not found in the empty JSON string", DayScheduleDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DayScheduleDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DayScheduleDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("intervals") != null && !jsonObj.get("intervals").isJsonNull()) {
        JsonArray jsonArrayintervals = jsonObj.getAsJsonArray("intervals");
        if (jsonArrayintervals != null) {
          // ensure the json data is an array
          if (!jsonObj.get("intervals").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `intervals` to be an array in the JSON string but got `%s`", jsonObj.get("intervals").toString()));
          }

          // validate the optional field `intervals` (array)
          for (int i = 0; i < jsonArrayintervals.size(); i++) {
            TimeIntervalDTO.validateJsonElement(jsonArrayintervals.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DayScheduleDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DayScheduleDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DayScheduleDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DayScheduleDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<DayScheduleDTO>() {
           @Override
           public void write(JsonWriter out, DayScheduleDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DayScheduleDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DayScheduleDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DayScheduleDTO
   * @throws IOException if the JSON string is invalid with respect to DayScheduleDTO
   */
  public static DayScheduleDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DayScheduleDTO.class);
  }

  /**
   * Convert an instance of DayScheduleDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

