/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * Response after successfully creating a delivery
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubCreateDeliveryResponse {
  public static final String SERIALIZED_NAME_DELIVERY_ID = "deliveryId";
  @SerializedName(SERIALIZED_NAME_DELIVERY_ID)
  @javax.annotation.Nullable
  private UUID deliveryId;

  /**
   * Type of delivery
   */
  @JsonAdapter(DeliveryTypeEnum.Adapter.class)
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE("STORE_IMMEDIATE"),
    
    FOOD_IMMEDIATE("FOOD_IMMEDIATE"),
    
    STORE_NEXT_DAY("STORE_NEXT_DAY");

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DeliveryTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeliveryTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeliveryTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DeliveryTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DeliveryTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DELIVERY_TYPE = "deliveryType";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TYPE)
  @javax.annotation.Nullable
  private DeliveryTypeEnum deliveryType;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_HUB_TRACKING_NUMBER = "hubTrackingNumber";
  @SerializedName(SERIALIZED_NAME_HUB_TRACKING_NUMBER)
  @javax.annotation.Nullable
  private String hubTrackingNumber;

  public static final String SERIALIZED_NAME_TRACKING_URL = "trackingUrl";
  @SerializedName(SERIALIZED_NAME_TRACKING_URL)
  @javax.annotation.Nullable
  private String trackingUrl;

  public HubCreateDeliveryResponse() {
  }

  public HubCreateDeliveryResponse deliveryId(@javax.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
    return this;
  }

  /**
   * Unique delivery identifier
   * @return deliveryId
   */
  @javax.annotation.Nullable
  public UUID getDeliveryId() {
    return deliveryId;
  }

  public void setDeliveryId(@javax.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
  }


  public HubCreateDeliveryResponse deliveryType(@javax.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Type of delivery
   * @return deliveryType
   */
  @javax.annotation.Nullable
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }

  public void setDeliveryType(@javax.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubCreateDeliveryResponse status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Current delivery status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public HubCreateDeliveryResponse hubTrackingNumber(@javax.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
    return this;
  }

  /**
   * Hub-assigned tracking number
   * @return hubTrackingNumber
   */
  @javax.annotation.Nullable
  public String getHubTrackingNumber() {
    return hubTrackingNumber;
  }

  public void setHubTrackingNumber(@javax.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
  }


  public HubCreateDeliveryResponse trackingUrl(@javax.annotation.Nullable String trackingUrl) {
    this.trackingUrl = trackingUrl;
    return this;
  }

  /**
   * Public tracking URL for the delivery
   * @return trackingUrl
   */
  @javax.annotation.Nullable
  public String getTrackingUrl() {
    return trackingUrl;
  }

  public void setTrackingUrl(@javax.annotation.Nullable String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubCreateDeliveryResponse hubCreateDeliveryResponse = (HubCreateDeliveryResponse) o;
    return Objects.equals(this.deliveryId, hubCreateDeliveryResponse.deliveryId) &&
        Objects.equals(this.deliveryType, hubCreateDeliveryResponse.deliveryType) &&
        Objects.equals(this.status, hubCreateDeliveryResponse.status) &&
        Objects.equals(this.hubTrackingNumber, hubCreateDeliveryResponse.hubTrackingNumber) &&
        Objects.equals(this.trackingUrl, hubCreateDeliveryResponse.trackingUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryId, deliveryType, status, hubTrackingNumber, trackingUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubCreateDeliveryResponse {\n");
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    hubTrackingNumber: ").append(toIndentedString(hubTrackingNumber)).append("\n");
    sb.append("    trackingUrl: ").append(toIndentedString(trackingUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("deliveryId");
    openapiFields.add("deliveryType");
    openapiFields.add("status");
    openapiFields.add("hubTrackingNumber");
    openapiFields.add("trackingUrl");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HubCreateDeliveryResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HubCreateDeliveryResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in HubCreateDeliveryResponse is not found in the empty JSON string", HubCreateDeliveryResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HubCreateDeliveryResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `HubCreateDeliveryResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("deliveryId") != null && !jsonObj.get("deliveryId").isJsonNull()) && !jsonObj.get("deliveryId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveryId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveryId").toString()));
      }
      if ((jsonObj.get("deliveryType") != null && !jsonObj.get("deliveryType").isJsonNull()) && !jsonObj.get("deliveryType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveryType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveryType").toString()));
      }
      // validate the optional field `deliveryType`
      if (jsonObj.get("deliveryType") != null && !jsonObj.get("deliveryType").isJsonNull()) {
        DeliveryTypeEnum.validateJsonElement(jsonObj.get("deliveryType"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("hubTrackingNumber") != null && !jsonObj.get("hubTrackingNumber").isJsonNull()) && !jsonObj.get("hubTrackingNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hubTrackingNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hubTrackingNumber").toString()));
      }
      if ((jsonObj.get("trackingUrl") != null && !jsonObj.get("trackingUrl").isJsonNull()) && !jsonObj.get("trackingUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trackingUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trackingUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HubCreateDeliveryResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HubCreateDeliveryResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HubCreateDeliveryResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HubCreateDeliveryResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<HubCreateDeliveryResponse>() {
           @Override
           public void write(JsonWriter out, HubCreateDeliveryResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HubCreateDeliveryResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HubCreateDeliveryResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HubCreateDeliveryResponse
   * @throws IOException if the JSON string is invalid with respect to HubCreateDeliveryResponse
   */
  public static HubCreateDeliveryResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HubCreateDeliveryResponse.class);
  }

  /**
   * Convert an instance of HubCreateDeliveryResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

