/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.delivery.hub.sdk.model.HubContactDTO;
import com.zipper.delivery.hub.sdk.model.HubItemDTO;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * Request to get a delivery price quote
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryQuoteRequest {
  /**
   * Type of delivery
   */
  @JsonAdapter(DeliveryTypeEnum.Adapter.class)
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE("STORE_IMMEDIATE"),
    
    FOOD_IMMEDIATE("FOOD_IMMEDIATE"),
    
    STORE_NEXT_DAY("STORE_NEXT_DAY");

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DeliveryTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeliveryTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeliveryTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DeliveryTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DeliveryTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DELIVERY_TYPE = "deliveryType";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TYPE)
  @javax.annotation.Nonnull
  private DeliveryTypeEnum deliveryType;

  public static final String SERIALIZED_NAME_PICKUP = "pickup";
  @SerializedName(SERIALIZED_NAME_PICKUP)
  @javax.annotation.Nullable
  private HubContactDTO pickup;

  public static final String SERIALIZED_NAME_DROPOFF = "dropoff";
  @SerializedName(SERIALIZED_NAME_DROPOFF)
  @javax.annotation.Nonnull
  private HubContactDTO dropoff;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  @javax.annotation.Nullable
  private List<HubItemDTO> items = new ArrayList<>();

  public static final String SERIALIZED_NAME_SCHEDULED_AT = "scheduledAt";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime scheduledAt;

  public static final String SERIALIZED_NAME_PICKUP_LOCATION_CODE = "pickupLocationCode";
  @SerializedName(SERIALIZED_NAME_PICKUP_LOCATION_CODE)
  @javax.annotation.Nullable
  private String pickupLocationCode;

  public HubDeliveryQuoteRequest() {
  }

  public HubDeliveryQuoteRequest deliveryType(@javax.annotation.Nonnull DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Type of delivery
   * @return deliveryType
   */
  @javax.annotation.Nonnull
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }

  public void setDeliveryType(@javax.annotation.Nonnull DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubDeliveryQuoteRequest pickup(@javax.annotation.Nullable HubContactDTO pickup) {
    this.pickup = pickup;
    return this;
  }

  /**
   * Pickup contact and location. Optional when pickupLocationCode is provided.
   * @return pickup
   */
  @javax.annotation.Nullable
  public HubContactDTO getPickup() {
    return pickup;
  }

  public void setPickup(@javax.annotation.Nullable HubContactDTO pickup) {
    this.pickup = pickup;
  }


  public HubDeliveryQuoteRequest dropoff(@javax.annotation.Nonnull HubContactDTO dropoff) {
    this.dropoff = dropoff;
    return this;
  }

  /**
   * Dropoff contact and location
   * @return dropoff
   */
  @javax.annotation.Nonnull
  public HubContactDTO getDropoff() {
    return dropoff;
  }

  public void setDropoff(@javax.annotation.Nonnull HubContactDTO dropoff) {
    this.dropoff = dropoff;
  }


  public HubDeliveryQuoteRequest items(@javax.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
    return this;
  }

  public HubDeliveryQuoteRequest addItemsItem(HubItemDTO itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * List of items for weight/size estimation
   * @return items
   */
  @javax.annotation.Nullable
  public List<HubItemDTO> getItems() {
    return items;
  }

  public void setItems(@javax.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
  }


  public HubDeliveryQuoteRequest scheduledAt(@javax.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
    return this;
  }

  /**
   * Scheduled pickup time (null for immediate)
   * @return scheduledAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getScheduledAt() {
    return scheduledAt;
  }

  public void setScheduledAt(@javax.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
  }


  public HubDeliveryQuoteRequest pickupLocationCode(@javax.annotation.Nullable String pickupLocationCode) {
    this.pickupLocationCode = pickupLocationCode;
    return this;
  }

  /**
   * Optional pickup location code. When set, pickup contact and address are auto-filled from the location.
   * @return pickupLocationCode
   */
  @javax.annotation.Nullable
  public String getPickupLocationCode() {
    return pickupLocationCode;
  }

  public void setPickupLocationCode(@javax.annotation.Nullable String pickupLocationCode) {
    this.pickupLocationCode = pickupLocationCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryQuoteRequest hubDeliveryQuoteRequest = (HubDeliveryQuoteRequest) o;
    return Objects.equals(this.deliveryType, hubDeliveryQuoteRequest.deliveryType) &&
        Objects.equals(this.pickup, hubDeliveryQuoteRequest.pickup) &&
        Objects.equals(this.dropoff, hubDeliveryQuoteRequest.dropoff) &&
        Objects.equals(this.items, hubDeliveryQuoteRequest.items) &&
        Objects.equals(this.scheduledAt, hubDeliveryQuoteRequest.scheduledAt) &&
        Objects.equals(this.pickupLocationCode, hubDeliveryQuoteRequest.pickupLocationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryType, pickup, dropoff, items, scheduledAt, pickupLocationCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryQuoteRequest {\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    pickup: ").append(toIndentedString(pickup)).append("\n");
    sb.append("    dropoff: ").append(toIndentedString(dropoff)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    scheduledAt: ").append(toIndentedString(scheduledAt)).append("\n");
    sb.append("    pickupLocationCode: ").append(toIndentedString(pickupLocationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("deliveryType");
    openapiFields.add("pickup");
    openapiFields.add("dropoff");
    openapiFields.add("items");
    openapiFields.add("scheduledAt");
    openapiFields.add("pickupLocationCode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("deliveryType");
    openapiRequiredFields.add("dropoff");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HubDeliveryQuoteRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HubDeliveryQuoteRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in HubDeliveryQuoteRequest is not found in the empty JSON string", HubDeliveryQuoteRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HubDeliveryQuoteRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `HubDeliveryQuoteRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HubDeliveryQuoteRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("deliveryType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveryType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveryType").toString()));
      }
      // validate the required field `deliveryType`
      DeliveryTypeEnum.validateJsonElement(jsonObj.get("deliveryType"));
      // validate the optional field `pickup`
      if (jsonObj.get("pickup") != null && !jsonObj.get("pickup").isJsonNull()) {
        HubContactDTO.validateJsonElement(jsonObj.get("pickup"));
      }
      // validate the required field `dropoff`
      HubContactDTO.validateJsonElement(jsonObj.get("dropoff"));
      if (jsonObj.get("items") != null && !jsonObj.get("items").isJsonNull()) {
        JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
        if (jsonArrayitems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
          }

          // validate the optional field `items` (array)
          for (int i = 0; i < jsonArrayitems.size(); i++) {
            HubItemDTO.validateJsonElement(jsonArrayitems.get(i));
          };
        }
      }
      if ((jsonObj.get("pickupLocationCode") != null && !jsonObj.get("pickupLocationCode").isJsonNull()) && !jsonObj.get("pickupLocationCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pickupLocationCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pickupLocationCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HubDeliveryQuoteRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HubDeliveryQuoteRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HubDeliveryQuoteRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HubDeliveryQuoteRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<HubDeliveryQuoteRequest>() {
           @Override
           public void write(JsonWriter out, HubDeliveryQuoteRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HubDeliveryQuoteRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HubDeliveryQuoteRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HubDeliveryQuoteRequest
   * @throws IOException if the JSON string is invalid with respect to HubDeliveryQuoteRequest
   */
  public static HubDeliveryQuoteRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HubDeliveryQuoteRequest.class);
  }

  /**
   * Convert an instance of HubDeliveryQuoteRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

