/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.delivery.hub.sdk.model.HubDeliveryLocationDTO;
import com.zipper.delivery.hub.sdk.model.HubItemDTO;
import com.zipper.delivery.hub.sdk.model.HubStatusEventDTO;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * Full delivery status including tracking and history
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryStatusResponse {
  public static final String SERIALIZED_NAME_DELIVERY_ID = "deliveryId";
  @SerializedName(SERIALIZED_NAME_DELIVERY_ID)
  @javax.annotation.Nullable
  private UUID deliveryId;

  /**
   * Type of delivery
   */
  @JsonAdapter(DeliveryTypeEnum.Adapter.class)
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE("STORE_IMMEDIATE"),
    
    FOOD_IMMEDIATE("FOOD_IMMEDIATE"),
    
    STORE_NEXT_DAY("STORE_NEXT_DAY");

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DeliveryTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeliveryTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeliveryTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DeliveryTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DeliveryTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DELIVERY_TYPE = "deliveryType";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TYPE)
  @javax.annotation.Nullable
  private DeliveryTypeEnum deliveryType;

  /**
   * Current delivery status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("PENDING"),
    
    DISPATCHED("DISPATCHED"),
    
    PROVIDER_ACCEPTED("PROVIDER_ACCEPTED"),
    
    ASSIGNED("ASSIGNED"),
    
    READY_FOR_PICKUP("READY_FOR_PICKUP"),
    
    PICKED_UP("PICKED_UP"),
    
    IN_TRANSIT("IN_TRANSIT"),
    
    DELIVERED("DELIVERED"),
    
    CANCELLED("CANCELLED"),
    
    FAILED("FAILED"),
    
    REJECTED("REJECTED"),
    
    AWAITING_DRIVER("AWAITING_DRIVER");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  /**
   * Carrier provider handling the delivery
   */
  @JsonAdapter(ProviderEnum.Adapter.class)
  public enum ProviderEnum {
    ZIPPERG("ZIPPERG"),
    
    ZIPPERW("ZIPPERW"),
    
    ZIPPERK("ZIPPERK");

    private String value;

    ProviderEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProviderEnum fromValue(String value) {
      for (ProviderEnum b : ProviderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProviderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProviderEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProviderEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProviderEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProviderEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @javax.annotation.Nullable
  private ProviderEnum provider;

  public static final String SERIALIZED_NAME_PROVIDER_TRACKING_ID = "providerTrackingId";
  @SerializedName(SERIALIZED_NAME_PROVIDER_TRACKING_ID)
  @javax.annotation.Nullable
  private String providerTrackingId;

  public static final String SERIALIZED_NAME_HUB_TRACKING_NUMBER = "hubTrackingNumber";
  @SerializedName(SERIALIZED_NAME_HUB_TRACKING_NUMBER)
  @javax.annotation.Nullable
  private String hubTrackingNumber;

  public static final String SERIALIZED_NAME_HUB_ORDER_ID = "hubOrderId";
  @SerializedName(SERIALIZED_NAME_HUB_ORDER_ID)
  @javax.annotation.Nullable
  private String hubOrderId;

  public static final String SERIALIZED_NAME_HUB_BARCODE = "hubBarcode";
  @SerializedName(SERIALIZED_NAME_HUB_BARCODE)
  @javax.annotation.Nullable
  private String hubBarcode;

  public static final String SERIALIZED_NAME_ESTIMATED_ARRIVAL = "estimatedArrival";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_ARRIVAL)
  @javax.annotation.Nullable
  private OffsetDateTime estimatedArrival;

  public static final String SERIALIZED_NAME_TRACKING_URL = "trackingUrl";
  @SerializedName(SERIALIZED_NAME_TRACKING_URL)
  @javax.annotation.Nullable
  private String trackingUrl;

  public static final String SERIALIZED_NAME_STATUS_HISTORY = "statusHistory";
  @SerializedName(SERIALIZED_NAME_STATUS_HISTORY)
  @javax.annotation.Nullable
  private List<HubStatusEventDTO> statusHistory = new ArrayList<>();

  public static final String SERIALIZED_NAME_PROOF_OF_DELIVERY_URL = "proofOfDeliveryUrl";
  @SerializedName(SERIALIZED_NAME_PROOF_OF_DELIVERY_URL)
  @javax.annotation.Nullable
  private String proofOfDeliveryUrl;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  @javax.annotation.Nullable
  private List<HubItemDTO> items = new ArrayList<>();

  public static final String SERIALIZED_NAME_PICKUP_CONTACT_NAME = "pickupContactName";
  @SerializedName(SERIALIZED_NAME_PICKUP_CONTACT_NAME)
  @javax.annotation.Nullable
  private String pickupContactName;

  public static final String SERIALIZED_NAME_PICKUP_CONTACT_PHONE = "pickupContactPhone";
  @SerializedName(SERIALIZED_NAME_PICKUP_CONTACT_PHONE)
  @javax.annotation.Nullable
  private String pickupContactPhone;

  public static final String SERIALIZED_NAME_PICKUP_EMAIL = "pickupEmail";
  @SerializedName(SERIALIZED_NAME_PICKUP_EMAIL)
  @javax.annotation.Nullable
  private String pickupEmail;

  public static final String SERIALIZED_NAME_PICKUP_NOTES = "pickupNotes";
  @SerializedName(SERIALIZED_NAME_PICKUP_NOTES)
  @javax.annotation.Nullable
  private String pickupNotes;

  public static final String SERIALIZED_NAME_PICKUP_REFERENCE_NUMBER = "pickupReferenceNumber";
  @SerializedName(SERIALIZED_NAME_PICKUP_REFERENCE_NUMBER)
  @javax.annotation.Nullable
  private String pickupReferenceNumber;

  public static final String SERIALIZED_NAME_PICKUP_LOCATION = "pickupLocation";
  @SerializedName(SERIALIZED_NAME_PICKUP_LOCATION)
  @javax.annotation.Nullable
  private HubDeliveryLocationDTO pickupLocation;

  public static final String SERIALIZED_NAME_DROPOFF_CONTACT_NAME = "dropoffContactName";
  @SerializedName(SERIALIZED_NAME_DROPOFF_CONTACT_NAME)
  @javax.annotation.Nullable
  private String dropoffContactName;

  public static final String SERIALIZED_NAME_DROPOFF_CONTACT_PHONE = "dropoffContactPhone";
  @SerializedName(SERIALIZED_NAME_DROPOFF_CONTACT_PHONE)
  @javax.annotation.Nullable
  private String dropoffContactPhone;

  public static final String SERIALIZED_NAME_DROPOFF_EMAIL = "dropoffEmail";
  @SerializedName(SERIALIZED_NAME_DROPOFF_EMAIL)
  @javax.annotation.Nullable
  private String dropoffEmail;

  public static final String SERIALIZED_NAME_DROPOFF_NOTES = "dropoffNotes";
  @SerializedName(SERIALIZED_NAME_DROPOFF_NOTES)
  @javax.annotation.Nullable
  private String dropoffNotes;

  public static final String SERIALIZED_NAME_DROPOFF_LOCATION = "dropoffLocation";
  @SerializedName(SERIALIZED_NAME_DROPOFF_LOCATION)
  @javax.annotation.Nullable
  private HubDeliveryLocationDTO dropoffLocation;

  public HubDeliveryStatusResponse() {
  }

  public HubDeliveryStatusResponse deliveryId(@javax.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
    return this;
  }

  /**
   * Unique delivery identifier
   * @return deliveryId
   */
  @javax.annotation.Nullable
  public UUID getDeliveryId() {
    return deliveryId;
  }

  public void setDeliveryId(@javax.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
  }


  public HubDeliveryStatusResponse deliveryType(@javax.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Type of delivery
   * @return deliveryType
   */
  @javax.annotation.Nullable
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }

  public void setDeliveryType(@javax.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubDeliveryStatusResponse status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Current delivery status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public HubDeliveryStatusResponse provider(@javax.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Carrier provider handling the delivery
   * @return provider
   */
  @javax.annotation.Nullable
  public ProviderEnum getProvider() {
    return provider;
  }

  public void setProvider(@javax.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
  }


  public HubDeliveryStatusResponse providerTrackingId(@javax.annotation.Nullable String providerTrackingId) {
    this.providerTrackingId = providerTrackingId;
    return this;
  }

  /**
   * Tracking ID from the carrier provider
   * @return providerTrackingId
   */
  @javax.annotation.Nullable
  public String getProviderTrackingId() {
    return providerTrackingId;
  }

  public void setProviderTrackingId(@javax.annotation.Nullable String providerTrackingId) {
    this.providerTrackingId = providerTrackingId;
  }


  public HubDeliveryStatusResponse hubTrackingNumber(@javax.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
    return this;
  }

  /**
   * Hub tracking number
   * @return hubTrackingNumber
   */
  @javax.annotation.Nullable
  public String getHubTrackingNumber() {
    return hubTrackingNumber;
  }

  public void setHubTrackingNumber(@javax.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
  }


  public HubDeliveryStatusResponse hubOrderId(@javax.annotation.Nullable String hubOrderId) {
    this.hubOrderId = hubOrderId;
    return this;
  }

  /**
   * Hub order ID
   * @return hubOrderId
   */
  @javax.annotation.Nullable
  public String getHubOrderId() {
    return hubOrderId;
  }

  public void setHubOrderId(@javax.annotation.Nullable String hubOrderId) {
    this.hubOrderId = hubOrderId;
  }


  public HubDeliveryStatusResponse hubBarcode(@javax.annotation.Nullable String hubBarcode) {
    this.hubBarcode = hubBarcode;
    return this;
  }

  /**
   * Hub barcode
   * @return hubBarcode
   */
  @javax.annotation.Nullable
  public String getHubBarcode() {
    return hubBarcode;
  }

  public void setHubBarcode(@javax.annotation.Nullable String hubBarcode) {
    this.hubBarcode = hubBarcode;
  }


  public HubDeliveryStatusResponse estimatedArrival(@javax.annotation.Nullable OffsetDateTime estimatedArrival) {
    this.estimatedArrival = estimatedArrival;
    return this;
  }

  /**
   * Estimated arrival time
   * @return estimatedArrival
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEstimatedArrival() {
    return estimatedArrival;
  }

  public void setEstimatedArrival(@javax.annotation.Nullable OffsetDateTime estimatedArrival) {
    this.estimatedArrival = estimatedArrival;
  }


  public HubDeliveryStatusResponse trackingUrl(@javax.annotation.Nullable String trackingUrl) {
    this.trackingUrl = trackingUrl;
    return this;
  }

  /**
   * Public tracking URL for the delivery recipient
   * @return trackingUrl
   */
  @javax.annotation.Nullable
  public String getTrackingUrl() {
    return trackingUrl;
  }

  public void setTrackingUrl(@javax.annotation.Nullable String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }


  public HubDeliveryStatusResponse statusHistory(@javax.annotation.Nullable List<HubStatusEventDTO> statusHistory) {
    this.statusHistory = statusHistory;
    return this;
  }

  public HubDeliveryStatusResponse addStatusHistoryItem(HubStatusEventDTO statusHistoryItem) {
    if (this.statusHistory == null) {
      this.statusHistory = new ArrayList<>();
    }
    this.statusHistory.add(statusHistoryItem);
    return this;
  }

  /**
   * Chronological list of status changes
   * @return statusHistory
   */
  @javax.annotation.Nullable
  public List<HubStatusEventDTO> getStatusHistory() {
    return statusHistory;
  }

  public void setStatusHistory(@javax.annotation.Nullable List<HubStatusEventDTO> statusHistory) {
    this.statusHistory = statusHistory;
  }


  public HubDeliveryStatusResponse proofOfDeliveryUrl(@javax.annotation.Nullable String proofOfDeliveryUrl) {
    this.proofOfDeliveryUrl = proofOfDeliveryUrl;
    return this;
  }

  /**
   * URL to the proof-of-delivery image (available after delivery)
   * @return proofOfDeliveryUrl
   */
  @javax.annotation.Nullable
  public String getProofOfDeliveryUrl() {
    return proofOfDeliveryUrl;
  }

  public void setProofOfDeliveryUrl(@javax.annotation.Nullable String proofOfDeliveryUrl) {
    this.proofOfDeliveryUrl = proofOfDeliveryUrl;
  }


  public HubDeliveryStatusResponse items(@javax.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
    return this;
  }

  public HubDeliveryStatusResponse addItemsItem(HubItemDTO itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Items included in the delivery
   * @return items
   */
  @javax.annotation.Nullable
  public List<HubItemDTO> getItems() {
    return items;
  }

  public void setItems(@javax.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
  }


  public HubDeliveryStatusResponse pickupContactName(@javax.annotation.Nullable String pickupContactName) {
    this.pickupContactName = pickupContactName;
    return this;
  }

  /**
   * Pickup contact name
   * @return pickupContactName
   */
  @javax.annotation.Nullable
  public String getPickupContactName() {
    return pickupContactName;
  }

  public void setPickupContactName(@javax.annotation.Nullable String pickupContactName) {
    this.pickupContactName = pickupContactName;
  }


  public HubDeliveryStatusResponse pickupContactPhone(@javax.annotation.Nullable String pickupContactPhone) {
    this.pickupContactPhone = pickupContactPhone;
    return this;
  }

  /**
   * Pickup contact phone number
   * @return pickupContactPhone
   */
  @javax.annotation.Nullable
  public String getPickupContactPhone() {
    return pickupContactPhone;
  }

  public void setPickupContactPhone(@javax.annotation.Nullable String pickupContactPhone) {
    this.pickupContactPhone = pickupContactPhone;
  }


  public HubDeliveryStatusResponse pickupEmail(@javax.annotation.Nullable String pickupEmail) {
    this.pickupEmail = pickupEmail;
    return this;
  }

  /**
   * Pickup contact email
   * @return pickupEmail
   */
  @javax.annotation.Nullable
  public String getPickupEmail() {
    return pickupEmail;
  }

  public void setPickupEmail(@javax.annotation.Nullable String pickupEmail) {
    this.pickupEmail = pickupEmail;
  }


  public HubDeliveryStatusResponse pickupNotes(@javax.annotation.Nullable String pickupNotes) {
    this.pickupNotes = pickupNotes;
    return this;
  }

  /**
   * Pickup notes or instructions
   * @return pickupNotes
   */
  @javax.annotation.Nullable
  public String getPickupNotes() {
    return pickupNotes;
  }

  public void setPickupNotes(@javax.annotation.Nullable String pickupNotes) {
    this.pickupNotes = pickupNotes;
  }


  public HubDeliveryStatusResponse pickupReferenceNumber(@javax.annotation.Nullable String pickupReferenceNumber) {
    this.pickupReferenceNumber = pickupReferenceNumber;
    return this;
  }

  /**
   * Pickup reference number used by the driver to collect the package (e.g., invoice number, warehouse release code)
   * @return pickupReferenceNumber
   */
  @javax.annotation.Nullable
  public String getPickupReferenceNumber() {
    return pickupReferenceNumber;
  }

  public void setPickupReferenceNumber(@javax.annotation.Nullable String pickupReferenceNumber) {
    this.pickupReferenceNumber = pickupReferenceNumber;
  }


  public HubDeliveryStatusResponse pickupLocation(@javax.annotation.Nullable HubDeliveryLocationDTO pickupLocation) {
    this.pickupLocation = pickupLocation;
    return this;
  }

  /**
   * Pickup location details
   * @return pickupLocation
   */
  @javax.annotation.Nullable
  public HubDeliveryLocationDTO getPickupLocation() {
    return pickupLocation;
  }

  public void setPickupLocation(@javax.annotation.Nullable HubDeliveryLocationDTO pickupLocation) {
    this.pickupLocation = pickupLocation;
  }


  public HubDeliveryStatusResponse dropoffContactName(@javax.annotation.Nullable String dropoffContactName) {
    this.dropoffContactName = dropoffContactName;
    return this;
  }

  /**
   * Dropoff contact name
   * @return dropoffContactName
   */
  @javax.annotation.Nullable
  public String getDropoffContactName() {
    return dropoffContactName;
  }

  public void setDropoffContactName(@javax.annotation.Nullable String dropoffContactName) {
    this.dropoffContactName = dropoffContactName;
  }


  public HubDeliveryStatusResponse dropoffContactPhone(@javax.annotation.Nullable String dropoffContactPhone) {
    this.dropoffContactPhone = dropoffContactPhone;
    return this;
  }

  /**
   * Dropoff contact phone number
   * @return dropoffContactPhone
   */
  @javax.annotation.Nullable
  public String getDropoffContactPhone() {
    return dropoffContactPhone;
  }

  public void setDropoffContactPhone(@javax.annotation.Nullable String dropoffContactPhone) {
    this.dropoffContactPhone = dropoffContactPhone;
  }


  public HubDeliveryStatusResponse dropoffEmail(@javax.annotation.Nullable String dropoffEmail) {
    this.dropoffEmail = dropoffEmail;
    return this;
  }

  /**
   * Dropoff contact email
   * @return dropoffEmail
   */
  @javax.annotation.Nullable
  public String getDropoffEmail() {
    return dropoffEmail;
  }

  public void setDropoffEmail(@javax.annotation.Nullable String dropoffEmail) {
    this.dropoffEmail = dropoffEmail;
  }


  public HubDeliveryStatusResponse dropoffNotes(@javax.annotation.Nullable String dropoffNotes) {
    this.dropoffNotes = dropoffNotes;
    return this;
  }

  /**
   * Dropoff notes or instructions
   * @return dropoffNotes
   */
  @javax.annotation.Nullable
  public String getDropoffNotes() {
    return dropoffNotes;
  }

  public void setDropoffNotes(@javax.annotation.Nullable String dropoffNotes) {
    this.dropoffNotes = dropoffNotes;
  }


  public HubDeliveryStatusResponse dropoffLocation(@javax.annotation.Nullable HubDeliveryLocationDTO dropoffLocation) {
    this.dropoffLocation = dropoffLocation;
    return this;
  }

  /**
   * Dropoff location details
   * @return dropoffLocation
   */
  @javax.annotation.Nullable
  public HubDeliveryLocationDTO getDropoffLocation() {
    return dropoffLocation;
  }

  public void setDropoffLocation(@javax.annotation.Nullable HubDeliveryLocationDTO dropoffLocation) {
    this.dropoffLocation = dropoffLocation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryStatusResponse hubDeliveryStatusResponse = (HubDeliveryStatusResponse) o;
    return Objects.equals(this.deliveryId, hubDeliveryStatusResponse.deliveryId) &&
        Objects.equals(this.deliveryType, hubDeliveryStatusResponse.deliveryType) &&
        Objects.equals(this.status, hubDeliveryStatusResponse.status) &&
        Objects.equals(this.provider, hubDeliveryStatusResponse.provider) &&
        Objects.equals(this.providerTrackingId, hubDeliveryStatusResponse.providerTrackingId) &&
        Objects.equals(this.hubTrackingNumber, hubDeliveryStatusResponse.hubTrackingNumber) &&
        Objects.equals(this.hubOrderId, hubDeliveryStatusResponse.hubOrderId) &&
        Objects.equals(this.hubBarcode, hubDeliveryStatusResponse.hubBarcode) &&
        Objects.equals(this.estimatedArrival, hubDeliveryStatusResponse.estimatedArrival) &&
        Objects.equals(this.trackingUrl, hubDeliveryStatusResponse.trackingUrl) &&
        Objects.equals(this.statusHistory, hubDeliveryStatusResponse.statusHistory) &&
        Objects.equals(this.proofOfDeliveryUrl, hubDeliveryStatusResponse.proofOfDeliveryUrl) &&
        Objects.equals(this.items, hubDeliveryStatusResponse.items) &&
        Objects.equals(this.pickupContactName, hubDeliveryStatusResponse.pickupContactName) &&
        Objects.equals(this.pickupContactPhone, hubDeliveryStatusResponse.pickupContactPhone) &&
        Objects.equals(this.pickupEmail, hubDeliveryStatusResponse.pickupEmail) &&
        Objects.equals(this.pickupNotes, hubDeliveryStatusResponse.pickupNotes) &&
        Objects.equals(this.pickupReferenceNumber, hubDeliveryStatusResponse.pickupReferenceNumber) &&
        Objects.equals(this.pickupLocation, hubDeliveryStatusResponse.pickupLocation) &&
        Objects.equals(this.dropoffContactName, hubDeliveryStatusResponse.dropoffContactName) &&
        Objects.equals(this.dropoffContactPhone, hubDeliveryStatusResponse.dropoffContactPhone) &&
        Objects.equals(this.dropoffEmail, hubDeliveryStatusResponse.dropoffEmail) &&
        Objects.equals(this.dropoffNotes, hubDeliveryStatusResponse.dropoffNotes) &&
        Objects.equals(this.dropoffLocation, hubDeliveryStatusResponse.dropoffLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryId, deliveryType, status, provider, providerTrackingId, hubTrackingNumber, hubOrderId, hubBarcode, estimatedArrival, trackingUrl, statusHistory, proofOfDeliveryUrl, items, pickupContactName, pickupContactPhone, pickupEmail, pickupNotes, pickupReferenceNumber, pickupLocation, dropoffContactName, dropoffContactPhone, dropoffEmail, dropoffNotes, dropoffLocation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryStatusResponse {\n");
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    providerTrackingId: ").append(toIndentedString(providerTrackingId)).append("\n");
    sb.append("    hubTrackingNumber: ").append(toIndentedString(hubTrackingNumber)).append("\n");
    sb.append("    hubOrderId: ").append(toIndentedString(hubOrderId)).append("\n");
    sb.append("    hubBarcode: ").append(toIndentedString(hubBarcode)).append("\n");
    sb.append("    estimatedArrival: ").append(toIndentedString(estimatedArrival)).append("\n");
    sb.append("    trackingUrl: ").append(toIndentedString(trackingUrl)).append("\n");
    sb.append("    statusHistory: ").append(toIndentedString(statusHistory)).append("\n");
    sb.append("    proofOfDeliveryUrl: ").append(toIndentedString(proofOfDeliveryUrl)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    pickupContactName: ").append(toIndentedString(pickupContactName)).append("\n");
    sb.append("    pickupContactPhone: ").append(toIndentedString(pickupContactPhone)).append("\n");
    sb.append("    pickupEmail: ").append(toIndentedString(pickupEmail)).append("\n");
    sb.append("    pickupNotes: ").append(toIndentedString(pickupNotes)).append("\n");
    sb.append("    pickupReferenceNumber: ").append(toIndentedString(pickupReferenceNumber)).append("\n");
    sb.append("    pickupLocation: ").append(toIndentedString(pickupLocation)).append("\n");
    sb.append("    dropoffContactName: ").append(toIndentedString(dropoffContactName)).append("\n");
    sb.append("    dropoffContactPhone: ").append(toIndentedString(dropoffContactPhone)).append("\n");
    sb.append("    dropoffEmail: ").append(toIndentedString(dropoffEmail)).append("\n");
    sb.append("    dropoffNotes: ").append(toIndentedString(dropoffNotes)).append("\n");
    sb.append("    dropoffLocation: ").append(toIndentedString(dropoffLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("deliveryId");
    openapiFields.add("deliveryType");
    openapiFields.add("status");
    openapiFields.add("provider");
    openapiFields.add("providerTrackingId");
    openapiFields.add("hubTrackingNumber");
    openapiFields.add("hubOrderId");
    openapiFields.add("hubBarcode");
    openapiFields.add("estimatedArrival");
    openapiFields.add("trackingUrl");
    openapiFields.add("statusHistory");
    openapiFields.add("proofOfDeliveryUrl");
    openapiFields.add("items");
    openapiFields.add("pickupContactName");
    openapiFields.add("pickupContactPhone");
    openapiFields.add("pickupEmail");
    openapiFields.add("pickupNotes");
    openapiFields.add("pickupReferenceNumber");
    openapiFields.add("pickupLocation");
    openapiFields.add("dropoffContactName");
    openapiFields.add("dropoffContactPhone");
    openapiFields.add("dropoffEmail");
    openapiFields.add("dropoffNotes");
    openapiFields.add("dropoffLocation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HubDeliveryStatusResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HubDeliveryStatusResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in HubDeliveryStatusResponse is not found in the empty JSON string", HubDeliveryStatusResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HubDeliveryStatusResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `HubDeliveryStatusResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("deliveryId") != null && !jsonObj.get("deliveryId").isJsonNull()) && !jsonObj.get("deliveryId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveryId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveryId").toString()));
      }
      if ((jsonObj.get("deliveryType") != null && !jsonObj.get("deliveryType").isJsonNull()) && !jsonObj.get("deliveryType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveryType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveryType").toString()));
      }
      // validate the optional field `deliveryType`
      if (jsonObj.get("deliveryType") != null && !jsonObj.get("deliveryType").isJsonNull()) {
        DeliveryTypeEnum.validateJsonElement(jsonObj.get("deliveryType"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      // validate the optional field `provider`
      if (jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) {
        ProviderEnum.validateJsonElement(jsonObj.get("provider"));
      }
      if ((jsonObj.get("providerTrackingId") != null && !jsonObj.get("providerTrackingId").isJsonNull()) && !jsonObj.get("providerTrackingId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerTrackingId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("providerTrackingId").toString()));
      }
      if ((jsonObj.get("hubTrackingNumber") != null && !jsonObj.get("hubTrackingNumber").isJsonNull()) && !jsonObj.get("hubTrackingNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hubTrackingNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hubTrackingNumber").toString()));
      }
      if ((jsonObj.get("hubOrderId") != null && !jsonObj.get("hubOrderId").isJsonNull()) && !jsonObj.get("hubOrderId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hubOrderId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hubOrderId").toString()));
      }
      if ((jsonObj.get("hubBarcode") != null && !jsonObj.get("hubBarcode").isJsonNull()) && !jsonObj.get("hubBarcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hubBarcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hubBarcode").toString()));
      }
      if ((jsonObj.get("trackingUrl") != null && !jsonObj.get("trackingUrl").isJsonNull()) && !jsonObj.get("trackingUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trackingUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trackingUrl").toString()));
      }
      if (jsonObj.get("statusHistory") != null && !jsonObj.get("statusHistory").isJsonNull()) {
        JsonArray jsonArraystatusHistory = jsonObj.getAsJsonArray("statusHistory");
        if (jsonArraystatusHistory != null) {
          // ensure the json data is an array
          if (!jsonObj.get("statusHistory").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `statusHistory` to be an array in the JSON string but got `%s`", jsonObj.get("statusHistory").toString()));
          }

          // validate the optional field `statusHistory` (array)
          for (int i = 0; i < jsonArraystatusHistory.size(); i++) {
            HubStatusEventDTO.validateJsonElement(jsonArraystatusHistory.get(i));
          };
        }
      }
      if ((jsonObj.get("proofOfDeliveryUrl") != null && !jsonObj.get("proofOfDeliveryUrl").isJsonNull()) && !jsonObj.get("proofOfDeliveryUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `proofOfDeliveryUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("proofOfDeliveryUrl").toString()));
      }
      if (jsonObj.get("items") != null && !jsonObj.get("items").isJsonNull()) {
        JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
        if (jsonArrayitems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
          }

          // validate the optional field `items` (array)
          for (int i = 0; i < jsonArrayitems.size(); i++) {
            HubItemDTO.validateJsonElement(jsonArrayitems.get(i));
          };
        }
      }
      if ((jsonObj.get("pickupContactName") != null && !jsonObj.get("pickupContactName").isJsonNull()) && !jsonObj.get("pickupContactName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pickupContactName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pickupContactName").toString()));
      }
      if ((jsonObj.get("pickupContactPhone") != null && !jsonObj.get("pickupContactPhone").isJsonNull()) && !jsonObj.get("pickupContactPhone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pickupContactPhone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pickupContactPhone").toString()));
      }
      if ((jsonObj.get("pickupEmail") != null && !jsonObj.get("pickupEmail").isJsonNull()) && !jsonObj.get("pickupEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pickupEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pickupEmail").toString()));
      }
      if ((jsonObj.get("pickupNotes") != null && !jsonObj.get("pickupNotes").isJsonNull()) && !jsonObj.get("pickupNotes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pickupNotes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pickupNotes").toString()));
      }
      if ((jsonObj.get("pickupReferenceNumber") != null && !jsonObj.get("pickupReferenceNumber").isJsonNull()) && !jsonObj.get("pickupReferenceNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pickupReferenceNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pickupReferenceNumber").toString()));
      }
      // validate the optional field `pickupLocation`
      if (jsonObj.get("pickupLocation") != null && !jsonObj.get("pickupLocation").isJsonNull()) {
        HubDeliveryLocationDTO.validateJsonElement(jsonObj.get("pickupLocation"));
      }
      if ((jsonObj.get("dropoffContactName") != null && !jsonObj.get("dropoffContactName").isJsonNull()) && !jsonObj.get("dropoffContactName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dropoffContactName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dropoffContactName").toString()));
      }
      if ((jsonObj.get("dropoffContactPhone") != null && !jsonObj.get("dropoffContactPhone").isJsonNull()) && !jsonObj.get("dropoffContactPhone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dropoffContactPhone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dropoffContactPhone").toString()));
      }
      if ((jsonObj.get("dropoffEmail") != null && !jsonObj.get("dropoffEmail").isJsonNull()) && !jsonObj.get("dropoffEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dropoffEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dropoffEmail").toString()));
      }
      if ((jsonObj.get("dropoffNotes") != null && !jsonObj.get("dropoffNotes").isJsonNull()) && !jsonObj.get("dropoffNotes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dropoffNotes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dropoffNotes").toString()));
      }
      // validate the optional field `dropoffLocation`
      if (jsonObj.get("dropoffLocation") != null && !jsonObj.get("dropoffLocation").isJsonNull()) {
        HubDeliveryLocationDTO.validateJsonElement(jsonObj.get("dropoffLocation"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HubDeliveryStatusResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HubDeliveryStatusResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HubDeliveryStatusResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HubDeliveryStatusResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<HubDeliveryStatusResponse>() {
           @Override
           public void write(JsonWriter out, HubDeliveryStatusResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HubDeliveryStatusResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HubDeliveryStatusResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HubDeliveryStatusResponse
   * @throws IOException if the JSON string is invalid with respect to HubDeliveryStatusResponse
   */
  public static HubDeliveryStatusResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HubDeliveryStatusResponse.class);
  }

  /**
   * Convert an instance of HubDeliveryStatusResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

