/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * Currently-assigned courier (admin views only)
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryCourierDTO {
  public static final String SERIALIZED_NAME_PROVIDER_DRIVER_ID = "providerDriverId";
  @SerializedName(SERIALIZED_NAME_PROVIDER_DRIVER_ID)
  @javax.annotation.Nullable
  private String providerDriverId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  @javax.annotation.Nullable
  private String phone;

  public static final String SERIALIZED_NAME_PHOTO_URL = "photoUrl";
  @SerializedName(SERIALIZED_NAME_PHOTO_URL)
  @javax.annotation.Nullable
  private String photoUrl;

  public static final String SERIALIZED_NAME_RATING = "rating";
  @SerializedName(SERIALIZED_NAME_RATING)
  @javax.annotation.Nullable
  private Double rating;

  /**
   * Gets or Sets vehicleType
   */
  @JsonAdapter(VehicleTypeEnum.Adapter.class)
  public enum VehicleTypeEnum {
    BICYCLE("BICYCLE"),
    
    MOTORCYCLE("MOTORCYCLE"),
    
    CAR("CAR"),
    
    VAN("VAN"),
    
    TRUCK("TRUCK"),
    
    ON_FOOT("ON_FOOT"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    VehicleTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VehicleTypeEnum fromValue(String value) {
      for (VehicleTypeEnum b : VehicleTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<VehicleTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VehicleTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VehicleTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return VehicleTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      VehicleTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_VEHICLE_TYPE = "vehicleType";
  @SerializedName(SERIALIZED_NAME_VEHICLE_TYPE)
  @javax.annotation.Nullable
  private VehicleTypeEnum vehicleType;

  public static final String SERIALIZED_NAME_RAW_VEHICLE_TYPE = "rawVehicleType";
  @SerializedName(SERIALIZED_NAME_RAW_VEHICLE_TYPE)
  @javax.annotation.Nullable
  private String rawVehicleType;

  public static final String SERIALIZED_NAME_LICENSE_PLATE = "licensePlate";
  @SerializedName(SERIALIZED_NAME_LICENSE_PLATE)
  @javax.annotation.Nullable
  private String licensePlate;

  public static final String SERIALIZED_NAME_MAKE = "make";
  @SerializedName(SERIALIZED_NAME_MAKE)
  @javax.annotation.Nullable
  private String make;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  @javax.annotation.Nullable
  private String model;

  public static final String SERIALIZED_NAME_COLOR = "color";
  @SerializedName(SERIALIZED_NAME_COLOR)
  @javax.annotation.Nullable
  private String color;

  public static final String SERIALIZED_NAME_LAT = "lat";
  @SerializedName(SERIALIZED_NAME_LAT)
  @javax.annotation.Nullable
  private Double lat;

  public static final String SERIALIZED_NAME_LNG = "lng";
  @SerializedName(SERIALIZED_NAME_LNG)
  @javax.annotation.Nullable
  private Double lng;

  public static final String SERIALIZED_NAME_ASSIGNED_AT = "assignedAt";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime assignedAt;

  public HubDeliveryCourierDTO() {
  }

  public HubDeliveryCourierDTO providerDriverId(@javax.annotation.Nullable String providerDriverId) {
    this.providerDriverId = providerDriverId;
    return this;
  }

  /**
   * Get providerDriverId
   * @return providerDriverId
   */
  @javax.annotation.Nullable
  public String getProviderDriverId() {
    return providerDriverId;
  }

  public void setProviderDriverId(@javax.annotation.Nullable String providerDriverId) {
    this.providerDriverId = providerDriverId;
  }


  public HubDeliveryCourierDTO name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public HubDeliveryCourierDTO phone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @javax.annotation.Nullable
  public String getPhone() {
    return phone;
  }

  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public HubDeliveryCourierDTO photoUrl(@javax.annotation.Nullable String photoUrl) {
    this.photoUrl = photoUrl;
    return this;
  }

  /**
   * Get photoUrl
   * @return photoUrl
   */
  @javax.annotation.Nullable
  public String getPhotoUrl() {
    return photoUrl;
  }

  public void setPhotoUrl(@javax.annotation.Nullable String photoUrl) {
    this.photoUrl = photoUrl;
  }


  public HubDeliveryCourierDTO rating(@javax.annotation.Nullable Double rating) {
    this.rating = rating;
    return this;
  }

  /**
   * Get rating
   * @return rating
   */
  @javax.annotation.Nullable
  public Double getRating() {
    return rating;
  }

  public void setRating(@javax.annotation.Nullable Double rating) {
    this.rating = rating;
  }


  public HubDeliveryCourierDTO vehicleType(@javax.annotation.Nullable VehicleTypeEnum vehicleType) {
    this.vehicleType = vehicleType;
    return this;
  }

  /**
   * Get vehicleType
   * @return vehicleType
   */
  @javax.annotation.Nullable
  public VehicleTypeEnum getVehicleType() {
    return vehicleType;
  }

  public void setVehicleType(@javax.annotation.Nullable VehicleTypeEnum vehicleType) {
    this.vehicleType = vehicleType;
  }


  public HubDeliveryCourierDTO rawVehicleType(@javax.annotation.Nullable String rawVehicleType) {
    this.rawVehicleType = rawVehicleType;
    return this;
  }

  /**
   * Get rawVehicleType
   * @return rawVehicleType
   */
  @javax.annotation.Nullable
  public String getRawVehicleType() {
    return rawVehicleType;
  }

  public void setRawVehicleType(@javax.annotation.Nullable String rawVehicleType) {
    this.rawVehicleType = rawVehicleType;
  }


  public HubDeliveryCourierDTO licensePlate(@javax.annotation.Nullable String licensePlate) {
    this.licensePlate = licensePlate;
    return this;
  }

  /**
   * Get licensePlate
   * @return licensePlate
   */
  @javax.annotation.Nullable
  public String getLicensePlate() {
    return licensePlate;
  }

  public void setLicensePlate(@javax.annotation.Nullable String licensePlate) {
    this.licensePlate = licensePlate;
  }


  public HubDeliveryCourierDTO make(@javax.annotation.Nullable String make) {
    this.make = make;
    return this;
  }

  /**
   * Get make
   * @return make
   */
  @javax.annotation.Nullable
  public String getMake() {
    return make;
  }

  public void setMake(@javax.annotation.Nullable String make) {
    this.make = make;
  }


  public HubDeliveryCourierDTO model(@javax.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  public String getModel() {
    return model;
  }

  public void setModel(@javax.annotation.Nullable String model) {
    this.model = model;
  }


  public HubDeliveryCourierDTO color(@javax.annotation.Nullable String color) {
    this.color = color;
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @javax.annotation.Nullable
  public String getColor() {
    return color;
  }

  public void setColor(@javax.annotation.Nullable String color) {
    this.color = color;
  }


  public HubDeliveryCourierDTO lat(@javax.annotation.Nullable Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * Get lat
   * @return lat
   */
  @javax.annotation.Nullable
  public Double getLat() {
    return lat;
  }

  public void setLat(@javax.annotation.Nullable Double lat) {
    this.lat = lat;
  }


  public HubDeliveryCourierDTO lng(@javax.annotation.Nullable Double lng) {
    this.lng = lng;
    return this;
  }

  /**
   * Get lng
   * @return lng
   */
  @javax.annotation.Nullable
  public Double getLng() {
    return lng;
  }

  public void setLng(@javax.annotation.Nullable Double lng) {
    this.lng = lng;
  }


  public HubDeliveryCourierDTO assignedAt(@javax.annotation.Nullable OffsetDateTime assignedAt) {
    this.assignedAt = assignedAt;
    return this;
  }

  /**
   * Get assignedAt
   * @return assignedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getAssignedAt() {
    return assignedAt;
  }

  public void setAssignedAt(@javax.annotation.Nullable OffsetDateTime assignedAt) {
    this.assignedAt = assignedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryCourierDTO hubDeliveryCourierDTO = (HubDeliveryCourierDTO) o;
    return Objects.equals(this.providerDriverId, hubDeliveryCourierDTO.providerDriverId) &&
        Objects.equals(this.name, hubDeliveryCourierDTO.name) &&
        Objects.equals(this.phone, hubDeliveryCourierDTO.phone) &&
        Objects.equals(this.photoUrl, hubDeliveryCourierDTO.photoUrl) &&
        Objects.equals(this.rating, hubDeliveryCourierDTO.rating) &&
        Objects.equals(this.vehicleType, hubDeliveryCourierDTO.vehicleType) &&
        Objects.equals(this.rawVehicleType, hubDeliveryCourierDTO.rawVehicleType) &&
        Objects.equals(this.licensePlate, hubDeliveryCourierDTO.licensePlate) &&
        Objects.equals(this.make, hubDeliveryCourierDTO.make) &&
        Objects.equals(this.model, hubDeliveryCourierDTO.model) &&
        Objects.equals(this.color, hubDeliveryCourierDTO.color) &&
        Objects.equals(this.lat, hubDeliveryCourierDTO.lat) &&
        Objects.equals(this.lng, hubDeliveryCourierDTO.lng) &&
        Objects.equals(this.assignedAt, hubDeliveryCourierDTO.assignedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(providerDriverId, name, phone, photoUrl, rating, vehicleType, rawVehicleType, licensePlate, make, model, color, lat, lng, assignedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryCourierDTO {\n");
    sb.append("    providerDriverId: ").append(toIndentedString(providerDriverId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    photoUrl: ").append(toIndentedString(photoUrl)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    vehicleType: ").append(toIndentedString(vehicleType)).append("\n");
    sb.append("    rawVehicleType: ").append(toIndentedString(rawVehicleType)).append("\n");
    sb.append("    licensePlate: ").append(toIndentedString(licensePlate)).append("\n");
    sb.append("    make: ").append(toIndentedString(make)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    assignedAt: ").append(toIndentedString(assignedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("providerDriverId");
    openapiFields.add("name");
    openapiFields.add("phone");
    openapiFields.add("photoUrl");
    openapiFields.add("rating");
    openapiFields.add("vehicleType");
    openapiFields.add("rawVehicleType");
    openapiFields.add("licensePlate");
    openapiFields.add("make");
    openapiFields.add("model");
    openapiFields.add("color");
    openapiFields.add("lat");
    openapiFields.add("lng");
    openapiFields.add("assignedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HubDeliveryCourierDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HubDeliveryCourierDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in HubDeliveryCourierDTO is not found in the empty JSON string", HubDeliveryCourierDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HubDeliveryCourierDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `HubDeliveryCourierDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("providerDriverId") != null && !jsonObj.get("providerDriverId").isJsonNull()) && !jsonObj.get("providerDriverId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerDriverId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("providerDriverId").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      if ((jsonObj.get("photoUrl") != null && !jsonObj.get("photoUrl").isJsonNull()) && !jsonObj.get("photoUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `photoUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("photoUrl").toString()));
      }
      if ((jsonObj.get("vehicleType") != null && !jsonObj.get("vehicleType").isJsonNull()) && !jsonObj.get("vehicleType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vehicleType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vehicleType").toString()));
      }
      // validate the optional field `vehicleType`
      if (jsonObj.get("vehicleType") != null && !jsonObj.get("vehicleType").isJsonNull()) {
        VehicleTypeEnum.validateJsonElement(jsonObj.get("vehicleType"));
      }
      if ((jsonObj.get("rawVehicleType") != null && !jsonObj.get("rawVehicleType").isJsonNull()) && !jsonObj.get("rawVehicleType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rawVehicleType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rawVehicleType").toString()));
      }
      if ((jsonObj.get("licensePlate") != null && !jsonObj.get("licensePlate").isJsonNull()) && !jsonObj.get("licensePlate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `licensePlate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("licensePlate").toString()));
      }
      if ((jsonObj.get("make") != null && !jsonObj.get("make").isJsonNull()) && !jsonObj.get("make").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `make` to be a primitive type in the JSON string but got `%s`", jsonObj.get("make").toString()));
      }
      if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) && !jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
      if ((jsonObj.get("color") != null && !jsonObj.get("color").isJsonNull()) && !jsonObj.get("color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("color").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HubDeliveryCourierDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HubDeliveryCourierDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HubDeliveryCourierDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HubDeliveryCourierDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<HubDeliveryCourierDTO>() {
           @Override
           public void write(JsonWriter out, HubDeliveryCourierDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HubDeliveryCourierDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HubDeliveryCourierDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HubDeliveryCourierDTO
   * @throws IOException if the JSON string is invalid with respect to HubDeliveryCourierDTO
   */
  public static HubDeliveryCourierDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HubDeliveryCourierDTO.class);
  }

  /**
   * Convert an instance of HubDeliveryCourierDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

