/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * Label metadata and asset URLs for a delivery
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryLabelResponse {
  public static final String SERIALIZED_NAME_BARCODE = "barcode";
  @SerializedName(SERIALIZED_NAME_BARCODE)
  @javax.annotation.Nullable
  private String barcode;

  public static final String SERIALIZED_NAME_BARCODE_IMAGE = "barcodeImage";
  @SerializedName(SERIALIZED_NAME_BARCODE_IMAGE)
  @javax.annotation.Nullable
  private String barcodeImage;

  public static final String SERIALIZED_NAME_QR_CODE = "qrCode";
  @SerializedName(SERIALIZED_NAME_QR_CODE)
  @javax.annotation.Nullable
  private String qrCode;

  public static final String SERIALIZED_NAME_LABEL_PDF = "labelPdf";
  @SerializedName(SERIALIZED_NAME_LABEL_PDF)
  @javax.annotation.Nullable
  private String labelPdf;

  public HubDeliveryLabelResponse() {
  }

  public HubDeliveryLabelResponse barcode(@javax.annotation.Nullable String barcode) {
    this.barcode = barcode;
    return this;
  }

  /**
   * Barcode value (tracking number or barcode)
   * @return barcode
   */
  @javax.annotation.Nullable
  public String getBarcode() {
    return barcode;
  }

  public void setBarcode(@javax.annotation.Nullable String barcode) {
    this.barcode = barcode;
  }


  public HubDeliveryLabelResponse barcodeImage(@javax.annotation.Nullable String barcodeImage) {
    this.barcodeImage = barcodeImage;
    return this;
  }

  /**
   * URL to the barcode image (PNG)
   * @return barcodeImage
   */
  @javax.annotation.Nullable
  public String getBarcodeImage() {
    return barcodeImage;
  }

  public void setBarcodeImage(@javax.annotation.Nullable String barcodeImage) {
    this.barcodeImage = barcodeImage;
  }


  public HubDeliveryLabelResponse qrCode(@javax.annotation.Nullable String qrCode) {
    this.qrCode = qrCode;
    return this;
  }

  /**
   * URL to the QR code image (PNG)
   * @return qrCode
   */
  @javax.annotation.Nullable
  public String getQrCode() {
    return qrCode;
  }

  public void setQrCode(@javax.annotation.Nullable String qrCode) {
    this.qrCode = qrCode;
  }


  public HubDeliveryLabelResponse labelPdf(@javax.annotation.Nullable String labelPdf) {
    this.labelPdf = labelPdf;
    return this;
  }

  /**
   * URL to the label PDF
   * @return labelPdf
   */
  @javax.annotation.Nullable
  public String getLabelPdf() {
    return labelPdf;
  }

  public void setLabelPdf(@javax.annotation.Nullable String labelPdf) {
    this.labelPdf = labelPdf;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryLabelResponse hubDeliveryLabelResponse = (HubDeliveryLabelResponse) o;
    return Objects.equals(this.barcode, hubDeliveryLabelResponse.barcode) &&
        Objects.equals(this.barcodeImage, hubDeliveryLabelResponse.barcodeImage) &&
        Objects.equals(this.qrCode, hubDeliveryLabelResponse.qrCode) &&
        Objects.equals(this.labelPdf, hubDeliveryLabelResponse.labelPdf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(barcode, barcodeImage, qrCode, labelPdf);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryLabelResponse {\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    barcodeImage: ").append(toIndentedString(barcodeImage)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("    labelPdf: ").append(toIndentedString(labelPdf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("barcode");
    openapiFields.add("barcodeImage");
    openapiFields.add("qrCode");
    openapiFields.add("labelPdf");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HubDeliveryLabelResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HubDeliveryLabelResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in HubDeliveryLabelResponse is not found in the empty JSON string", HubDeliveryLabelResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HubDeliveryLabelResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `HubDeliveryLabelResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("barcode") != null && !jsonObj.get("barcode").isJsonNull()) && !jsonObj.get("barcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `barcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("barcode").toString()));
      }
      if ((jsonObj.get("barcodeImage") != null && !jsonObj.get("barcodeImage").isJsonNull()) && !jsonObj.get("barcodeImage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `barcodeImage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("barcodeImage").toString()));
      }
      if ((jsonObj.get("qrCode") != null && !jsonObj.get("qrCode").isJsonNull()) && !jsonObj.get("qrCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `qrCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("qrCode").toString()));
      }
      if ((jsonObj.get("labelPdf") != null && !jsonObj.get("labelPdf").isJsonNull()) && !jsonObj.get("labelPdf").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `labelPdf` to be a primitive type in the JSON string but got `%s`", jsonObj.get("labelPdf").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HubDeliveryLabelResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HubDeliveryLabelResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HubDeliveryLabelResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HubDeliveryLabelResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<HubDeliveryLabelResponse>() {
           @Override
           public void write(JsonWriter out, HubDeliveryLabelResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HubDeliveryLabelResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HubDeliveryLabelResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HubDeliveryLabelResponse
   * @throws IOException if the JSON string is invalid with respect to HubDeliveryLabelResponse
   */
  public static HubDeliveryLabelResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HubDeliveryLabelResponse.class);
  }

  /**
   * Convert an instance of HubDeliveryLabelResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

