/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.delivery.hub.sdk.model.PublicCourierInfo;
import com.zipper.delivery.hub.sdk.model.PublicDropoffInfo;
import com.zipper.delivery.hub.sdk.model.PublicItemInfo;
import com.zipper.delivery.hub.sdk.model.PublicPackageDetails;
import com.zipper.delivery.hub.sdk.model.PublicPickupInfo;
import com.zipper.delivery.hub.sdk.model.PublicStatusEvent;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * PublicTrackingResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PublicTrackingResponse {
  public static final String SERIALIZED_NAME_TRACKING_NUMBER = "trackingNumber";
  @SerializedName(SERIALIZED_NAME_TRACKING_NUMBER)
  @javax.annotation.Nullable
  private String trackingNumber;

  public static final String SERIALIZED_NAME_HUB_BARCODE = "hubBarcode";
  @SerializedName(SERIALIZED_NAME_HUB_BARCODE)
  @javax.annotation.Nullable
  private String hubBarcode;

  public static final String SERIALIZED_NAME_PACKAGE_DETAILS = "packageDetails";
  @SerializedName(SERIALIZED_NAME_PACKAGE_DETAILS)
  @javax.annotation.Nullable
  private PublicPackageDetails packageDetails;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    CONFIRMED("CONFIRMED"),
    
    LOOKING_FOR_DRIVER("LOOKING_FOR_DRIVER"),
    
    DRIVER_ASSIGNED("DRIVER_ASSIGNED"),
    
    PREPARING("PREPARING"),
    
    PICKED_UP("PICKED_UP"),
    
    ON_THE_WAY("ON_THE_WAY"),
    
    DELIVERED("DELIVERED"),
    
    CANCELLED("CANCELLED"),
    
    UNSUCCESSFUL("UNSUCCESSFUL");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_DELIVERY_TYPE = "deliveryType";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TYPE)
  @javax.annotation.Nullable
  private String deliveryType;

  public static final String SERIALIZED_NAME_ESTIMATED_PICKUP_AT = "estimatedPickupAt";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_PICKUP_AT)
  @javax.annotation.Nullable
  private OffsetDateTime estimatedPickupAt;

  public static final String SERIALIZED_NAME_ESTIMATED_DROPOFF_AT = "estimatedDropoffAt";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_DROPOFF_AT)
  @javax.annotation.Nullable
  private OffsetDateTime estimatedDropoffAt;

  public static final String SERIALIZED_NAME_PICKUP = "pickup";
  @SerializedName(SERIALIZED_NAME_PICKUP)
  @javax.annotation.Nullable
  private PublicPickupInfo pickup;

  public static final String SERIALIZED_NAME_DROPOFF = "dropoff";
  @SerializedName(SERIALIZED_NAME_DROPOFF)
  @javax.annotation.Nullable
  private PublicDropoffInfo dropoff;

  public static final String SERIALIZED_NAME_COURIER = "courier";
  @SerializedName(SERIALIZED_NAME_COURIER)
  @javax.annotation.Nullable
  private PublicCourierInfo courier;

  public static final String SERIALIZED_NAME_STATUS_TIMELINE = "statusTimeline";
  @SerializedName(SERIALIZED_NAME_STATUS_TIMELINE)
  @javax.annotation.Nullable
  private List<PublicStatusEvent> statusTimeline = new ArrayList<>();

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  @javax.annotation.Nullable
  private List<PublicItemInfo> items = new ArrayList<>();

  public static final String SERIALIZED_NAME_PROOF_OF_DELIVERY_URL = "proofOfDeliveryUrl";
  @SerializedName(SERIALIZED_NAME_PROOF_OF_DELIVERY_URL)
  @javax.annotation.Nullable
  private String proofOfDeliveryUrl;

  public PublicTrackingResponse() {
  }

  public PublicTrackingResponse trackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

  /**
   * Get trackingNumber
   * @return trackingNumber
   */
  @javax.annotation.Nullable
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }


  public PublicTrackingResponse hubBarcode(@javax.annotation.Nullable String hubBarcode) {
    this.hubBarcode = hubBarcode;
    return this;
  }

  /**
   * Get hubBarcode
   * @return hubBarcode
   */
  @javax.annotation.Nullable
  public String getHubBarcode() {
    return hubBarcode;
  }

  public void setHubBarcode(@javax.annotation.Nullable String hubBarcode) {
    this.hubBarcode = hubBarcode;
  }


  public PublicTrackingResponse packageDetails(@javax.annotation.Nullable PublicPackageDetails packageDetails) {
    this.packageDetails = packageDetails;
    return this;
  }

  /**
   * Get packageDetails
   * @return packageDetails
   */
  @javax.annotation.Nullable
  public PublicPackageDetails getPackageDetails() {
    return packageDetails;
  }

  public void setPackageDetails(@javax.annotation.Nullable PublicPackageDetails packageDetails) {
    this.packageDetails = packageDetails;
  }


  public PublicTrackingResponse status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public PublicTrackingResponse deliveryType(@javax.annotation.Nullable String deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Get deliveryType
   * @return deliveryType
   */
  @javax.annotation.Nullable
  public String getDeliveryType() {
    return deliveryType;
  }

  public void setDeliveryType(@javax.annotation.Nullable String deliveryType) {
    this.deliveryType = deliveryType;
  }


  public PublicTrackingResponse estimatedPickupAt(@javax.annotation.Nullable OffsetDateTime estimatedPickupAt) {
    this.estimatedPickupAt = estimatedPickupAt;
    return this;
  }

  /**
   * Get estimatedPickupAt
   * @return estimatedPickupAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEstimatedPickupAt() {
    return estimatedPickupAt;
  }

  public void setEstimatedPickupAt(@javax.annotation.Nullable OffsetDateTime estimatedPickupAt) {
    this.estimatedPickupAt = estimatedPickupAt;
  }


  public PublicTrackingResponse estimatedDropoffAt(@javax.annotation.Nullable OffsetDateTime estimatedDropoffAt) {
    this.estimatedDropoffAt = estimatedDropoffAt;
    return this;
  }

  /**
   * Get estimatedDropoffAt
   * @return estimatedDropoffAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEstimatedDropoffAt() {
    return estimatedDropoffAt;
  }

  public void setEstimatedDropoffAt(@javax.annotation.Nullable OffsetDateTime estimatedDropoffAt) {
    this.estimatedDropoffAt = estimatedDropoffAt;
  }


  public PublicTrackingResponse pickup(@javax.annotation.Nullable PublicPickupInfo pickup) {
    this.pickup = pickup;
    return this;
  }

  /**
   * Get pickup
   * @return pickup
   */
  @javax.annotation.Nullable
  public PublicPickupInfo getPickup() {
    return pickup;
  }

  public void setPickup(@javax.annotation.Nullable PublicPickupInfo pickup) {
    this.pickup = pickup;
  }


  public PublicTrackingResponse dropoff(@javax.annotation.Nullable PublicDropoffInfo dropoff) {
    this.dropoff = dropoff;
    return this;
  }

  /**
   * Get dropoff
   * @return dropoff
   */
  @javax.annotation.Nullable
  public PublicDropoffInfo getDropoff() {
    return dropoff;
  }

  public void setDropoff(@javax.annotation.Nullable PublicDropoffInfo dropoff) {
    this.dropoff = dropoff;
  }


  public PublicTrackingResponse courier(@javax.annotation.Nullable PublicCourierInfo courier) {
    this.courier = courier;
    return this;
  }

  /**
   * Get courier
   * @return courier
   */
  @javax.annotation.Nullable
  public PublicCourierInfo getCourier() {
    return courier;
  }

  public void setCourier(@javax.annotation.Nullable PublicCourierInfo courier) {
    this.courier = courier;
  }


  public PublicTrackingResponse statusTimeline(@javax.annotation.Nullable List<PublicStatusEvent> statusTimeline) {
    this.statusTimeline = statusTimeline;
    return this;
  }

  public PublicTrackingResponse addStatusTimelineItem(PublicStatusEvent statusTimelineItem) {
    if (this.statusTimeline == null) {
      this.statusTimeline = new ArrayList<>();
    }
    this.statusTimeline.add(statusTimelineItem);
    return this;
  }

  /**
   * Get statusTimeline
   * @return statusTimeline
   */
  @javax.annotation.Nullable
  public List<PublicStatusEvent> getStatusTimeline() {
    return statusTimeline;
  }

  public void setStatusTimeline(@javax.annotation.Nullable List<PublicStatusEvent> statusTimeline) {
    this.statusTimeline = statusTimeline;
  }


  public PublicTrackingResponse items(@javax.annotation.Nullable List<PublicItemInfo> items) {
    this.items = items;
    return this;
  }

  public PublicTrackingResponse addItemsItem(PublicItemInfo itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
   */
  @javax.annotation.Nullable
  public List<PublicItemInfo> getItems() {
    return items;
  }

  public void setItems(@javax.annotation.Nullable List<PublicItemInfo> items) {
    this.items = items;
  }


  public PublicTrackingResponse proofOfDeliveryUrl(@javax.annotation.Nullable String proofOfDeliveryUrl) {
    this.proofOfDeliveryUrl = proofOfDeliveryUrl;
    return this;
  }

  /**
   * Get proofOfDeliveryUrl
   * @return proofOfDeliveryUrl
   */
  @javax.annotation.Nullable
  public String getProofOfDeliveryUrl() {
    return proofOfDeliveryUrl;
  }

  public void setProofOfDeliveryUrl(@javax.annotation.Nullable String proofOfDeliveryUrl) {
    this.proofOfDeliveryUrl = proofOfDeliveryUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicTrackingResponse publicTrackingResponse = (PublicTrackingResponse) o;
    return Objects.equals(this.trackingNumber, publicTrackingResponse.trackingNumber) &&
        Objects.equals(this.hubBarcode, publicTrackingResponse.hubBarcode) &&
        Objects.equals(this.packageDetails, publicTrackingResponse.packageDetails) &&
        Objects.equals(this.status, publicTrackingResponse.status) &&
        Objects.equals(this.deliveryType, publicTrackingResponse.deliveryType) &&
        Objects.equals(this.estimatedPickupAt, publicTrackingResponse.estimatedPickupAt) &&
        Objects.equals(this.estimatedDropoffAt, publicTrackingResponse.estimatedDropoffAt) &&
        Objects.equals(this.pickup, publicTrackingResponse.pickup) &&
        Objects.equals(this.dropoff, publicTrackingResponse.dropoff) &&
        Objects.equals(this.courier, publicTrackingResponse.courier) &&
        Objects.equals(this.statusTimeline, publicTrackingResponse.statusTimeline) &&
        Objects.equals(this.items, publicTrackingResponse.items) &&
        Objects.equals(this.proofOfDeliveryUrl, publicTrackingResponse.proofOfDeliveryUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trackingNumber, hubBarcode, packageDetails, status, deliveryType, estimatedPickupAt, estimatedDropoffAt, pickup, dropoff, courier, statusTimeline, items, proofOfDeliveryUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicTrackingResponse {\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    hubBarcode: ").append(toIndentedString(hubBarcode)).append("\n");
    sb.append("    packageDetails: ").append(toIndentedString(packageDetails)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    estimatedPickupAt: ").append(toIndentedString(estimatedPickupAt)).append("\n");
    sb.append("    estimatedDropoffAt: ").append(toIndentedString(estimatedDropoffAt)).append("\n");
    sb.append("    pickup: ").append(toIndentedString(pickup)).append("\n");
    sb.append("    dropoff: ").append(toIndentedString(dropoff)).append("\n");
    sb.append("    courier: ").append(toIndentedString(courier)).append("\n");
    sb.append("    statusTimeline: ").append(toIndentedString(statusTimeline)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    proofOfDeliveryUrl: ").append(toIndentedString(proofOfDeliveryUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("trackingNumber");
    openapiFields.add("hubBarcode");
    openapiFields.add("packageDetails");
    openapiFields.add("status");
    openapiFields.add("deliveryType");
    openapiFields.add("estimatedPickupAt");
    openapiFields.add("estimatedDropoffAt");
    openapiFields.add("pickup");
    openapiFields.add("dropoff");
    openapiFields.add("courier");
    openapiFields.add("statusTimeline");
    openapiFields.add("items");
    openapiFields.add("proofOfDeliveryUrl");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PublicTrackingResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PublicTrackingResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PublicTrackingResponse is not found in the empty JSON string", PublicTrackingResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PublicTrackingResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PublicTrackingResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("trackingNumber") != null && !jsonObj.get("trackingNumber").isJsonNull()) && !jsonObj.get("trackingNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trackingNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trackingNumber").toString()));
      }
      if ((jsonObj.get("hubBarcode") != null && !jsonObj.get("hubBarcode").isJsonNull()) && !jsonObj.get("hubBarcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hubBarcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hubBarcode").toString()));
      }
      // validate the optional field `packageDetails`
      if (jsonObj.get("packageDetails") != null && !jsonObj.get("packageDetails").isJsonNull()) {
        PublicPackageDetails.validateJsonElement(jsonObj.get("packageDetails"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("deliveryType") != null && !jsonObj.get("deliveryType").isJsonNull()) && !jsonObj.get("deliveryType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveryType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveryType").toString()));
      }
      // validate the optional field `pickup`
      if (jsonObj.get("pickup") != null && !jsonObj.get("pickup").isJsonNull()) {
        PublicPickupInfo.validateJsonElement(jsonObj.get("pickup"));
      }
      // validate the optional field `dropoff`
      if (jsonObj.get("dropoff") != null && !jsonObj.get("dropoff").isJsonNull()) {
        PublicDropoffInfo.validateJsonElement(jsonObj.get("dropoff"));
      }
      // validate the optional field `courier`
      if (jsonObj.get("courier") != null && !jsonObj.get("courier").isJsonNull()) {
        PublicCourierInfo.validateJsonElement(jsonObj.get("courier"));
      }
      if (jsonObj.get("statusTimeline") != null && !jsonObj.get("statusTimeline").isJsonNull()) {
        JsonArray jsonArraystatusTimeline = jsonObj.getAsJsonArray("statusTimeline");
        if (jsonArraystatusTimeline != null) {
          // ensure the json data is an array
          if (!jsonObj.get("statusTimeline").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `statusTimeline` to be an array in the JSON string but got `%s`", jsonObj.get("statusTimeline").toString()));
          }

          // validate the optional field `statusTimeline` (array)
          for (int i = 0; i < jsonArraystatusTimeline.size(); i++) {
            PublicStatusEvent.validateJsonElement(jsonArraystatusTimeline.get(i));
          };
        }
      }
      if (jsonObj.get("items") != null && !jsonObj.get("items").isJsonNull()) {
        JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
        if (jsonArrayitems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
          }

          // validate the optional field `items` (array)
          for (int i = 0; i < jsonArrayitems.size(); i++) {
            PublicItemInfo.validateJsonElement(jsonArrayitems.get(i));
          };
        }
      }
      if ((jsonObj.get("proofOfDeliveryUrl") != null && !jsonObj.get("proofOfDeliveryUrl").isJsonNull()) && !jsonObj.get("proofOfDeliveryUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `proofOfDeliveryUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("proofOfDeliveryUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PublicTrackingResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PublicTrackingResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PublicTrackingResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PublicTrackingResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PublicTrackingResponse>() {
           @Override
           public void write(JsonWriter out, PublicTrackingResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PublicTrackingResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PublicTrackingResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PublicTrackingResponse
   * @throws IOException if the JSON string is invalid with respect to PublicTrackingResponse
   */
  public static PublicTrackingResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PublicTrackingResponse.class);
  }

  /**
   * Convert an instance of PublicTrackingResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

