/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * PublicItemInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PublicItemInfo {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  @javax.annotation.Nullable
  private Integer quantity;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_WEIGHT_KG = "weightKg";
  @SerializedName(SERIALIZED_NAME_WEIGHT_KG)
  @javax.annotation.Nullable
  private Double weightKg;

  public static final String SERIALIZED_NAME_LENGTH_CM = "lengthCm";
  @SerializedName(SERIALIZED_NAME_LENGTH_CM)
  @javax.annotation.Nullable
  private Double lengthCm;

  public static final String SERIALIZED_NAME_WIDTH_CM = "widthCm";
  @SerializedName(SERIALIZED_NAME_WIDTH_CM)
  @javax.annotation.Nullable
  private Double widthCm;

  public static final String SERIALIZED_NAME_HEIGHT_CM = "heightCm";
  @SerializedName(SERIALIZED_NAME_HEIGHT_CM)
  @javax.annotation.Nullable
  private Double heightCm;

  public PublicItemInfo() {
  }

  public PublicItemInfo name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public PublicItemInfo quantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @javax.annotation.Nullable
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }


  public PublicItemInfo description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public PublicItemInfo weightKg(@javax.annotation.Nullable Double weightKg) {
    this.weightKg = weightKg;
    return this;
  }

  /**
   * Get weightKg
   * @return weightKg
   */
  @javax.annotation.Nullable
  public Double getWeightKg() {
    return weightKg;
  }

  public void setWeightKg(@javax.annotation.Nullable Double weightKg) {
    this.weightKg = weightKg;
  }


  public PublicItemInfo lengthCm(@javax.annotation.Nullable Double lengthCm) {
    this.lengthCm = lengthCm;
    return this;
  }

  /**
   * Get lengthCm
   * @return lengthCm
   */
  @javax.annotation.Nullable
  public Double getLengthCm() {
    return lengthCm;
  }

  public void setLengthCm(@javax.annotation.Nullable Double lengthCm) {
    this.lengthCm = lengthCm;
  }


  public PublicItemInfo widthCm(@javax.annotation.Nullable Double widthCm) {
    this.widthCm = widthCm;
    return this;
  }

  /**
   * Get widthCm
   * @return widthCm
   */
  @javax.annotation.Nullable
  public Double getWidthCm() {
    return widthCm;
  }

  public void setWidthCm(@javax.annotation.Nullable Double widthCm) {
    this.widthCm = widthCm;
  }


  public PublicItemInfo heightCm(@javax.annotation.Nullable Double heightCm) {
    this.heightCm = heightCm;
    return this;
  }

  /**
   * Get heightCm
   * @return heightCm
   */
  @javax.annotation.Nullable
  public Double getHeightCm() {
    return heightCm;
  }

  public void setHeightCm(@javax.annotation.Nullable Double heightCm) {
    this.heightCm = heightCm;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicItemInfo publicItemInfo = (PublicItemInfo) o;
    return Objects.equals(this.name, publicItemInfo.name) &&
        Objects.equals(this.quantity, publicItemInfo.quantity) &&
        Objects.equals(this.description, publicItemInfo.description) &&
        Objects.equals(this.weightKg, publicItemInfo.weightKg) &&
        Objects.equals(this.lengthCm, publicItemInfo.lengthCm) &&
        Objects.equals(this.widthCm, publicItemInfo.widthCm) &&
        Objects.equals(this.heightCm, publicItemInfo.heightCm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, quantity, description, weightKg, lengthCm, widthCm, heightCm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicItemInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    weightKg: ").append(toIndentedString(weightKg)).append("\n");
    sb.append("    lengthCm: ").append(toIndentedString(lengthCm)).append("\n");
    sb.append("    widthCm: ").append(toIndentedString(widthCm)).append("\n");
    sb.append("    heightCm: ").append(toIndentedString(heightCm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("quantity");
    openapiFields.add("description");
    openapiFields.add("weightKg");
    openapiFields.add("lengthCm");
    openapiFields.add("widthCm");
    openapiFields.add("heightCm");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PublicItemInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PublicItemInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PublicItemInfo is not found in the empty JSON string", PublicItemInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PublicItemInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PublicItemInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PublicItemInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PublicItemInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PublicItemInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PublicItemInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<PublicItemInfo>() {
           @Override
           public void write(JsonWriter out, PublicItemInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PublicItemInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PublicItemInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PublicItemInfo
   * @throws IOException if the JSON string is invalid with respect to PublicItemInfo
   */
  public static PublicItemInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PublicItemInfo.class);
  }

  /**
   * Convert an instance of PublicItemInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

