/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * RouteMeta
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class RouteMeta {
  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  @javax.annotation.Nullable
  private Double weight;

  public static final String SERIALIZED_NAME_WEIGHT_NAME = "weightName";
  @SerializedName(SERIALIZED_NAME_WEIGHT_NAME)
  @javax.annotation.Nullable
  private String weightName;

  public static final String SERIALIZED_NAME_PICKUP_SNAP_METERS = "pickupSnapMeters";
  @SerializedName(SERIALIZED_NAME_PICKUP_SNAP_METERS)
  @javax.annotation.Nullable
  private Double pickupSnapMeters;

  public static final String SERIALIZED_NAME_DROPOFF_SNAP_METERS = "dropoffSnapMeters";
  @SerializedName(SERIALIZED_NAME_DROPOFF_SNAP_METERS)
  @javax.annotation.Nullable
  private Double dropoffSnapMeters;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  @javax.annotation.Nullable
  private String summary;

  public RouteMeta() {
  }

  public RouteMeta weight(@javax.annotation.Nullable Double weight) {
    this.weight = weight;
    return this;
  }

  /**
   * Get weight
   * @return weight
   */
  @javax.annotation.Nullable
  public Double getWeight() {
    return weight;
  }

  public void setWeight(@javax.annotation.Nullable Double weight) {
    this.weight = weight;
  }


  public RouteMeta weightName(@javax.annotation.Nullable String weightName) {
    this.weightName = weightName;
    return this;
  }

  /**
   * Get weightName
   * @return weightName
   */
  @javax.annotation.Nullable
  public String getWeightName() {
    return weightName;
  }

  public void setWeightName(@javax.annotation.Nullable String weightName) {
    this.weightName = weightName;
  }


  public RouteMeta pickupSnapMeters(@javax.annotation.Nullable Double pickupSnapMeters) {
    this.pickupSnapMeters = pickupSnapMeters;
    return this;
  }

  /**
   * Get pickupSnapMeters
   * @return pickupSnapMeters
   */
  @javax.annotation.Nullable
  public Double getPickupSnapMeters() {
    return pickupSnapMeters;
  }

  public void setPickupSnapMeters(@javax.annotation.Nullable Double pickupSnapMeters) {
    this.pickupSnapMeters = pickupSnapMeters;
  }


  public RouteMeta dropoffSnapMeters(@javax.annotation.Nullable Double dropoffSnapMeters) {
    this.dropoffSnapMeters = dropoffSnapMeters;
    return this;
  }

  /**
   * Get dropoffSnapMeters
   * @return dropoffSnapMeters
   */
  @javax.annotation.Nullable
  public Double getDropoffSnapMeters() {
    return dropoffSnapMeters;
  }

  public void setDropoffSnapMeters(@javax.annotation.Nullable Double dropoffSnapMeters) {
    this.dropoffSnapMeters = dropoffSnapMeters;
  }


  public RouteMeta summary(@javax.annotation.Nullable String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nullable
  public String getSummary() {
    return summary;
  }

  public void setSummary(@javax.annotation.Nullable String summary) {
    this.summary = summary;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteMeta routeMeta = (RouteMeta) o;
    return Objects.equals(this.weight, routeMeta.weight) &&
        Objects.equals(this.weightName, routeMeta.weightName) &&
        Objects.equals(this.pickupSnapMeters, routeMeta.pickupSnapMeters) &&
        Objects.equals(this.dropoffSnapMeters, routeMeta.dropoffSnapMeters) &&
        Objects.equals(this.summary, routeMeta.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weight, weightName, pickupSnapMeters, dropoffSnapMeters, summary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteMeta {\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    weightName: ").append(toIndentedString(weightName)).append("\n");
    sb.append("    pickupSnapMeters: ").append(toIndentedString(pickupSnapMeters)).append("\n");
    sb.append("    dropoffSnapMeters: ").append(toIndentedString(dropoffSnapMeters)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("weight");
    openapiFields.add("weightName");
    openapiFields.add("pickupSnapMeters");
    openapiFields.add("dropoffSnapMeters");
    openapiFields.add("summary");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RouteMeta
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RouteMeta.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RouteMeta is not found in the empty JSON string", RouteMeta.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RouteMeta.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RouteMeta` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("weightName") != null && !jsonObj.get("weightName").isJsonNull()) && !jsonObj.get("weightName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `weightName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("weightName").toString()));
      }
      if ((jsonObj.get("summary") != null && !jsonObj.get("summary").isJsonNull()) && !jsonObj.get("summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("summary").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RouteMeta.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RouteMeta' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RouteMeta> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RouteMeta.class));

       return (TypeAdapter<T>) new TypeAdapter<RouteMeta>() {
           @Override
           public void write(JsonWriter out, RouteMeta value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RouteMeta read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RouteMeta given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RouteMeta
   * @throws IOException if the JSON string is invalid with respect to RouteMeta
   */
  public static RouteMeta fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RouteMeta.class);
  }

  /**
   * Convert an instance of RouteMeta to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

