/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.delivery.hub.sdk.model.OpeningHoursDTO;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.delivery.hub.sdk.JSON;

/**
 * Request to update an existing pickup location. All fields are optional for partial update.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class UpdatePickupLocationRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  /**
   * Type of pickup location
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    STORE("STORE"),
    
    WAREHOUSE("WAREHOUSE"),
    
    HUB("HUB");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private TypeEnum type;

  /**
   * Status of the location
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    INACTIVE("INACTIVE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_IS_DEFAULT = "isDefault";
  @SerializedName(SERIALIZED_NAME_IS_DEFAULT)
  @javax.annotation.Nullable
  private Boolean isDefault;

  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "addressLine1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  @javax.annotation.Nullable
  private String addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_LINE2 = "addressLine2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE2)
  @javax.annotation.Nullable
  private String addressLine2;

  public static final String SERIALIZED_NAME_HOUSE_NUMBER = "houseNumber";
  @SerializedName(SERIALIZED_NAME_HOUSE_NUMBER)
  @javax.annotation.Nullable
  private String houseNumber;

  public static final String SERIALIZED_NAME_ENTRANCE_FLOOR = "entranceFloor";
  @SerializedName(SERIALIZED_NAME_ENTRANCE_FLOOR)
  @javax.annotation.Nullable
  private String entranceFloor;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  @javax.annotation.Nullable
  private String city;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  @javax.annotation.Nullable
  private String region;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  @javax.annotation.Nullable
  private String postalCode;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  @javax.annotation.Nullable
  private String countryCode;

  public static final String SERIALIZED_NAME_LATITUDE = "latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  @javax.annotation.Nullable
  private Double latitude;

  public static final String SERIALIZED_NAME_LONGITUDE = "longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  @javax.annotation.Nullable
  private Double longitude;

  public static final String SERIALIZED_NAME_CONTACT_NAME = "contactName";
  @SerializedName(SERIALIZED_NAME_CONTACT_NAME)
  @javax.annotation.Nullable
  private String contactName;

  public static final String SERIALIZED_NAME_CONTACT_PHONE = "contactPhone";
  @SerializedName(SERIALIZED_NAME_CONTACT_PHONE)
  @javax.annotation.Nullable
  private String contactPhone;

  public static final String SERIALIZED_NAME_CONTACT_EMAIL = "contactEmail";
  @SerializedName(SERIALIZED_NAME_CONTACT_EMAIL)
  @javax.annotation.Nullable
  private String contactEmail;

  public static final String SERIALIZED_NAME_OPENING_HOURS = "openingHours";
  @SerializedName(SERIALIZED_NAME_OPENING_HOURS)
  @javax.annotation.Nullable
  private OpeningHoursDTO openingHours;

  public static final String SERIALIZED_NAME_DELIVERY_TYPE_CONFIG = "deliveryTypeConfig";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TYPE_CONFIG)
  @javax.annotation.Nullable
  private Map<String, Map<String, Object>> deliveryTypeConfig = new HashMap<>();

  public static final String SERIALIZED_NAME_PICKUP_INSTRUCTIONS = "pickupInstructions";
  @SerializedName(SERIALIZED_NAME_PICKUP_INSTRUCTIONS)
  @javax.annotation.Nullable
  private String pickupInstructions;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone;

  public UpdatePickupLocationRequest() {
  }

  public UpdatePickupLocationRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Display name for the location
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public UpdatePickupLocationRequest type(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Type of pickup location
   * @return type
   */
  @javax.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public UpdatePickupLocationRequest status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Status of the location
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public UpdatePickupLocationRequest isDefault(@javax.annotation.Nullable Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

  /**
   * Whether this is the default pickup location
   * @return isDefault
   */
  @javax.annotation.Nullable
  public Boolean getIsDefault() {
    return isDefault;
  }

  public void setIsDefault(@javax.annotation.Nullable Boolean isDefault) {
    this.isDefault = isDefault;
  }


  public UpdatePickupLocationRequest addressLine1(@javax.annotation.Nullable String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

  /**
   * Primary address line
   * @return addressLine1
   */
  @javax.annotation.Nullable
  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(@javax.annotation.Nullable String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public UpdatePickupLocationRequest addressLine2(@javax.annotation.Nullable String addressLine2) {
    this.addressLine2 = addressLine2;
    return this;
  }

  /**
   * Secondary address line
   * @return addressLine2
   */
  @javax.annotation.Nullable
  public String getAddressLine2() {
    return addressLine2;
  }

  public void setAddressLine2(@javax.annotation.Nullable String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public UpdatePickupLocationRequest houseNumber(@javax.annotation.Nullable String houseNumber) {
    this.houseNumber = houseNumber;
    return this;
  }

  /**
   * House number
   * @return houseNumber
   */
  @javax.annotation.Nullable
  public String getHouseNumber() {
    return houseNumber;
  }

  public void setHouseNumber(@javax.annotation.Nullable String houseNumber) {
    this.houseNumber = houseNumber;
  }


  public UpdatePickupLocationRequest entranceFloor(@javax.annotation.Nullable String entranceFloor) {
    this.entranceFloor = entranceFloor;
    return this;
  }

  /**
   * Entrance or floor
   * @return entranceFloor
   */
  @javax.annotation.Nullable
  public String getEntranceFloor() {
    return entranceFloor;
  }

  public void setEntranceFloor(@javax.annotation.Nullable String entranceFloor) {
    this.entranceFloor = entranceFloor;
  }


  public UpdatePickupLocationRequest city(@javax.annotation.Nullable String city) {
    this.city = city;
    return this;
  }

  /**
   * City name
   * @return city
   */
  @javax.annotation.Nullable
  public String getCity() {
    return city;
  }

  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }


  public UpdatePickupLocationRequest region(@javax.annotation.Nullable String region) {
    this.region = region;
    return this;
  }

  /**
   * Region or state
   * @return region
   */
  @javax.annotation.Nullable
  public String getRegion() {
    return region;
  }

  public void setRegion(@javax.annotation.Nullable String region) {
    this.region = region;
  }


  public UpdatePickupLocationRequest postalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Postal code
   * @return postalCode
   */
  @javax.annotation.Nullable
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
  }


  public UpdatePickupLocationRequest countryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * ISO country code
   * @return countryCode
   */
  @javax.annotation.Nullable
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }


  public UpdatePickupLocationRequest latitude(@javax.annotation.Nullable Double latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * Latitude coordinate
   * @return latitude
   */
  @javax.annotation.Nullable
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(@javax.annotation.Nullable Double latitude) {
    this.latitude = latitude;
  }


  public UpdatePickupLocationRequest longitude(@javax.annotation.Nullable Double longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * Longitude coordinate
   * @return longitude
   */
  @javax.annotation.Nullable
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(@javax.annotation.Nullable Double longitude) {
    this.longitude = longitude;
  }


  public UpdatePickupLocationRequest contactName(@javax.annotation.Nullable String contactName) {
    this.contactName = contactName;
    return this;
  }

  /**
   * Contact person name
   * @return contactName
   */
  @javax.annotation.Nullable
  public String getContactName() {
    return contactName;
  }

  public void setContactName(@javax.annotation.Nullable String contactName) {
    this.contactName = contactName;
  }


  public UpdatePickupLocationRequest contactPhone(@javax.annotation.Nullable String contactPhone) {
    this.contactPhone = contactPhone;
    return this;
  }

  /**
   * Contact phone number
   * @return contactPhone
   */
  @javax.annotation.Nullable
  public String getContactPhone() {
    return contactPhone;
  }

  public void setContactPhone(@javax.annotation.Nullable String contactPhone) {
    this.contactPhone = contactPhone;
  }


  public UpdatePickupLocationRequest contactEmail(@javax.annotation.Nullable String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

  /**
   * Contact email
   * @return contactEmail
   */
  @javax.annotation.Nullable
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(@javax.annotation.Nullable String contactEmail) {
    this.contactEmail = contactEmail;
  }


  public UpdatePickupLocationRequest openingHours(@javax.annotation.Nullable OpeningHoursDTO openingHours) {
    this.openingHours = openingHours;
    return this;
  }

  /**
   * Opening hours with interval support
   * @return openingHours
   */
  @javax.annotation.Nullable
  public OpeningHoursDTO getOpeningHours() {
    return openingHours;
  }

  public void setOpeningHours(@javax.annotation.Nullable OpeningHoursDTO openingHours) {
    this.openingHours = openingHours;
  }


  public UpdatePickupLocationRequest deliveryTypeConfig(@javax.annotation.Nullable Map<String, Map<String, Object>> deliveryTypeConfig) {
    this.deliveryTypeConfig = deliveryTypeConfig;
    return this;
  }

  public UpdatePickupLocationRequest putDeliveryTypeConfigItem(String key, Map<String, Object> deliveryTypeConfigItem) {
    if (this.deliveryTypeConfig == null) {
      this.deliveryTypeConfig = new HashMap<>();
    }
    this.deliveryTypeConfig.put(key, deliveryTypeConfigItem);
    return this;
  }

  /**
   * Per-delivery-type configuration
   * @return deliveryTypeConfig
   */
  @javax.annotation.Nullable
  public Map<String, Map<String, Object>> getDeliveryTypeConfig() {
    return deliveryTypeConfig;
  }

  public void setDeliveryTypeConfig(@javax.annotation.Nullable Map<String, Map<String, Object>> deliveryTypeConfig) {
    this.deliveryTypeConfig = deliveryTypeConfig;
  }


  public UpdatePickupLocationRequest pickupInstructions(@javax.annotation.Nullable String pickupInstructions) {
    this.pickupInstructions = pickupInstructions;
    return this;
  }

  /**
   * Instructions for pickup couriers
   * @return pickupInstructions
   */
  @javax.annotation.Nullable
  public String getPickupInstructions() {
    return pickupInstructions;
  }

  public void setPickupInstructions(@javax.annotation.Nullable String pickupInstructions) {
    this.pickupInstructions = pickupInstructions;
  }


  public UpdatePickupLocationRequest timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Timezone for opening hours validation
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePickupLocationRequest updatePickupLocationRequest = (UpdatePickupLocationRequest) o;
    return Objects.equals(this.name, updatePickupLocationRequest.name) &&
        Objects.equals(this.type, updatePickupLocationRequest.type) &&
        Objects.equals(this.status, updatePickupLocationRequest.status) &&
        Objects.equals(this.isDefault, updatePickupLocationRequest.isDefault) &&
        Objects.equals(this.addressLine1, updatePickupLocationRequest.addressLine1) &&
        Objects.equals(this.addressLine2, updatePickupLocationRequest.addressLine2) &&
        Objects.equals(this.houseNumber, updatePickupLocationRequest.houseNumber) &&
        Objects.equals(this.entranceFloor, updatePickupLocationRequest.entranceFloor) &&
        Objects.equals(this.city, updatePickupLocationRequest.city) &&
        Objects.equals(this.region, updatePickupLocationRequest.region) &&
        Objects.equals(this.postalCode, updatePickupLocationRequest.postalCode) &&
        Objects.equals(this.countryCode, updatePickupLocationRequest.countryCode) &&
        Objects.equals(this.latitude, updatePickupLocationRequest.latitude) &&
        Objects.equals(this.longitude, updatePickupLocationRequest.longitude) &&
        Objects.equals(this.contactName, updatePickupLocationRequest.contactName) &&
        Objects.equals(this.contactPhone, updatePickupLocationRequest.contactPhone) &&
        Objects.equals(this.contactEmail, updatePickupLocationRequest.contactEmail) &&
        Objects.equals(this.openingHours, updatePickupLocationRequest.openingHours) &&
        Objects.equals(this.deliveryTypeConfig, updatePickupLocationRequest.deliveryTypeConfig) &&
        Objects.equals(this.pickupInstructions, updatePickupLocationRequest.pickupInstructions) &&
        Objects.equals(this.timezone, updatePickupLocationRequest.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, status, isDefault, addressLine1, addressLine2, houseNumber, entranceFloor, city, region, postalCode, countryCode, latitude, longitude, contactName, contactPhone, contactEmail, openingHours, deliveryTypeConfig, pickupInstructions, timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePickupLocationRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    houseNumber: ").append(toIndentedString(houseNumber)).append("\n");
    sb.append("    entranceFloor: ").append(toIndentedString(entranceFloor)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    contactName: ").append(toIndentedString(contactName)).append("\n");
    sb.append("    contactPhone: ").append(toIndentedString(contactPhone)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    openingHours: ").append(toIndentedString(openingHours)).append("\n");
    sb.append("    deliveryTypeConfig: ").append(toIndentedString(deliveryTypeConfig)).append("\n");
    sb.append("    pickupInstructions: ").append(toIndentedString(pickupInstructions)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("type");
    openapiFields.add("status");
    openapiFields.add("isDefault");
    openapiFields.add("addressLine1");
    openapiFields.add("addressLine2");
    openapiFields.add("houseNumber");
    openapiFields.add("entranceFloor");
    openapiFields.add("city");
    openapiFields.add("region");
    openapiFields.add("postalCode");
    openapiFields.add("countryCode");
    openapiFields.add("latitude");
    openapiFields.add("longitude");
    openapiFields.add("contactName");
    openapiFields.add("contactPhone");
    openapiFields.add("contactEmail");
    openapiFields.add("openingHours");
    openapiFields.add("deliveryTypeConfig");
    openapiFields.add("pickupInstructions");
    openapiFields.add("timezone");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdatePickupLocationRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdatePickupLocationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdatePickupLocationRequest is not found in the empty JSON string", UpdatePickupLocationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdatePickupLocationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdatePickupLocationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        TypeEnum.validateJsonElement(jsonObj.get("type"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("addressLine1") != null && !jsonObj.get("addressLine1").isJsonNull()) && !jsonObj.get("addressLine1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressLine1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressLine1").toString()));
      }
      if ((jsonObj.get("addressLine2") != null && !jsonObj.get("addressLine2").isJsonNull()) && !jsonObj.get("addressLine2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressLine2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressLine2").toString()));
      }
      if ((jsonObj.get("houseNumber") != null && !jsonObj.get("houseNumber").isJsonNull()) && !jsonObj.get("houseNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `houseNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("houseNumber").toString()));
      }
      if ((jsonObj.get("entranceFloor") != null && !jsonObj.get("entranceFloor").isJsonNull()) && !jsonObj.get("entranceFloor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `entranceFloor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("entranceFloor").toString()));
      }
      if ((jsonObj.get("city") != null && !jsonObj.get("city").isJsonNull()) && !jsonObj.get("city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("city").toString()));
      }
      if ((jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull()) && !jsonObj.get("region").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
      }
      if ((jsonObj.get("postalCode") != null && !jsonObj.get("postalCode").isJsonNull()) && !jsonObj.get("postalCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `postalCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("postalCode").toString()));
      }
      if ((jsonObj.get("countryCode") != null && !jsonObj.get("countryCode").isJsonNull()) && !jsonObj.get("countryCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryCode").toString()));
      }
      if ((jsonObj.get("contactName") != null && !jsonObj.get("contactName").isJsonNull()) && !jsonObj.get("contactName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contactName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactName").toString()));
      }
      if ((jsonObj.get("contactPhone") != null && !jsonObj.get("contactPhone").isJsonNull()) && !jsonObj.get("contactPhone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contactPhone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactPhone").toString()));
      }
      if ((jsonObj.get("contactEmail") != null && !jsonObj.get("contactEmail").isJsonNull()) && !jsonObj.get("contactEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contactEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactEmail").toString()));
      }
      // validate the optional field `openingHours`
      if (jsonObj.get("openingHours") != null && !jsonObj.get("openingHours").isJsonNull()) {
        OpeningHoursDTO.validateJsonElement(jsonObj.get("openingHours"));
      }
      if ((jsonObj.get("pickupInstructions") != null && !jsonObj.get("pickupInstructions").isJsonNull()) && !jsonObj.get("pickupInstructions").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pickupInstructions` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pickupInstructions").toString()));
      }
      if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull()) && !jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdatePickupLocationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdatePickupLocationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdatePickupLocationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdatePickupLocationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdatePickupLocationRequest>() {
           @Override
           public void write(JsonWriter out, UpdatePickupLocationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdatePickupLocationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdatePickupLocationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdatePickupLocationRequest
   * @throws IOException if the JSON string is invalid with respect to UpdatePickupLocationRequest
   */
  public static UpdatePickupLocationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdatePickupLocationRequest.class);
  }

  /**
   * Convert an instance of UpdatePickupLocationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

