/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.api;

import com.zipper.delivery.hub.sdk.ApiCallback;
import com.zipper.delivery.hub.sdk.ApiClient;
import com.zipper.delivery.hub.sdk.ApiException;
import com.zipper.delivery.hub.sdk.ApiResponse;
import com.zipper.delivery.hub.sdk.Configuration;
import com.zipper.delivery.hub.sdk.Pair;
import com.zipper.delivery.hub.sdk.ProgressRequestBody;
import com.zipper.delivery.hub.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.delivery.hub.sdk.model.InternalPickupLocationDTO;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InternalPickupLocationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InternalPickupLocationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InternalPickupLocationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getById
     * @param id  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Location found </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Location not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByIdCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/delivery/v1/internal/pickup-locations/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByIdValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getById(Async)");
        }

        return getByIdCall(id, acceptLanguage, _callback);

    }

    /**
     * Get pickup location by external ID
     * Returns pickup location metadata. Used for service-to-service validation.
     * @param id  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return InternalPickupLocationDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Location found </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Location not found </td><td>  -  </td></tr>
     </table>
     */
    public InternalPickupLocationDTO getById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<InternalPickupLocationDTO> localVarResp = getByIdWithHttpInfo(id, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Get pickup location by external ID
     * Returns pickup location metadata. Used for service-to-service validation.
     * @param id  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;InternalPickupLocationDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Location found </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Location not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InternalPickupLocationDTO> getByIdWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = getByIdValidateBeforeCall(id, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<InternalPickupLocationDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get pickup location by external ID (asynchronously)
     * Returns pickup location metadata. Used for service-to-service validation.
     * @param id  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Location found </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Location not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByIdAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<InternalPickupLocationDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByIdValidateBeforeCall(id, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<InternalPickupLocationDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
