/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.api;

import com.zipper.delivery.hub.sdk.ApiCallback;
import com.zipper.delivery.hub.sdk.ApiClient;
import com.zipper.delivery.hub.sdk.ApiException;
import com.zipper.delivery.hub.sdk.ApiResponse;
import com.zipper.delivery.hub.sdk.Configuration;
import com.zipper.delivery.hub.sdk.Pair;
import com.zipper.delivery.hub.sdk.ProgressRequestBody;
import com.zipper.delivery.hub.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.delivery.hub.sdk.model.BulkUpsertPickupLocationRequest;
import com.zipper.delivery.hub.sdk.model.CreatePickupLocationRequest;
import com.zipper.delivery.hub.sdk.model.PageResponseListPickupLocationDTO;
import com.zipper.delivery.hub.sdk.model.PickupLocationDTO;
import com.zipper.delivery.hub.sdk.model.SearchPickupLocationsRequest;
import java.util.UUID;
import com.zipper.delivery.hub.sdk.model.UpdatePickupLocationRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PickupLocationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PickupLocationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PickupLocationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for bulkUpsertPickupLocations
     * @param bulkUpsertPickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Batch accepted for async processing </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call bulkUpsertPickupLocationsCall(@javax.annotation.Nonnull BulkUpsertPickupLocationRequest bulkUpsertPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = bulkUpsertPickupLocationRequest;

        // create path and map variables
        String localVarPath = "/delivery/v1/pickup-locations/bulk-upsert";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call bulkUpsertPickupLocationsValidateBeforeCall(@javax.annotation.Nonnull BulkUpsertPickupLocationRequest bulkUpsertPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'bulkUpsertPickupLocationRequest' is set
        if (bulkUpsertPickupLocationRequest == null) {
            throw new ApiException("Missing the required parameter 'bulkUpsertPickupLocationRequest' when calling bulkUpsertPickupLocations(Async)");
        }

        return bulkUpsertPickupLocationsCall(bulkUpsertPickupLocationRequest, acceptLanguage, _callback);

    }

    /**
     * Bulk upsert pickup locations (async)
     * Accepts a batch of pickup locations for create or update. Matching is by &#x60;code&#x60; — existing codes are updated, new codes are created. Processing is asynchronous via message queue. On completion, a webhook event &#x60;pickup_location_bulk_upsert_completed&#x60; is sent with results and any errors.
     * @param bulkUpsertPickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Batch accepted for async processing </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
     </table>
     */
    public void bulkUpsertPickupLocations(@javax.annotation.Nonnull BulkUpsertPickupLocationRequest bulkUpsertPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        bulkUpsertPickupLocationsWithHttpInfo(bulkUpsertPickupLocationRequest, acceptLanguage);
    }

    /**
     * Bulk upsert pickup locations (async)
     * Accepts a batch of pickup locations for create or update. Matching is by &#x60;code&#x60; — existing codes are updated, new codes are created. Processing is asynchronous via message queue. On completion, a webhook event &#x60;pickup_location_bulk_upsert_completed&#x60; is sent with results and any errors.
     * @param bulkUpsertPickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Batch accepted for async processing </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> bulkUpsertPickupLocationsWithHttpInfo(@javax.annotation.Nonnull BulkUpsertPickupLocationRequest bulkUpsertPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = bulkUpsertPickupLocationsValidateBeforeCall(bulkUpsertPickupLocationRequest, acceptLanguage, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Bulk upsert pickup locations (async) (asynchronously)
     * Accepts a batch of pickup locations for create or update. Matching is by &#x60;code&#x60; — existing codes are updated, new codes are created. Processing is asynchronous via message queue. On completion, a webhook event &#x60;pickup_location_bulk_upsert_completed&#x60; is sent with results and any errors.
     * @param bulkUpsertPickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Batch accepted for async processing </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call bulkUpsertPickupLocationsAsync(@javax.annotation.Nonnull BulkUpsertPickupLocationRequest bulkUpsertPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = bulkUpsertPickupLocationsValidateBeforeCall(bulkUpsertPickupLocationRequest, acceptLanguage, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for createPickupLocation
     * @param createPickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Pickup location created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Code already exists </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createPickupLocationCall(@javax.annotation.Nonnull CreatePickupLocationRequest createPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createPickupLocationRequest;

        // create path and map variables
        String localVarPath = "/delivery/v1/pickup-locations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createPickupLocationValidateBeforeCall(@javax.annotation.Nonnull CreatePickupLocationRequest createPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createPickupLocationRequest' is set
        if (createPickupLocationRequest == null) {
            throw new ApiException("Missing the required parameter 'createPickupLocationRequest' when calling createPickupLocation(Async)");
        }

        return createPickupLocationCall(createPickupLocationRequest, acceptLanguage, _callback);

    }

    /**
     * Create a pickup location
     * 
     * @param createPickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return PickupLocationDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Pickup location created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Code already exists </td><td>  -  </td></tr>
     </table>
     */
    public PickupLocationDTO createPickupLocation(@javax.annotation.Nonnull CreatePickupLocationRequest createPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<PickupLocationDTO> localVarResp = createPickupLocationWithHttpInfo(createPickupLocationRequest, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Create a pickup location
     * 
     * @param createPickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;PickupLocationDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Pickup location created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Code already exists </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PickupLocationDTO> createPickupLocationWithHttpInfo(@javax.annotation.Nonnull CreatePickupLocationRequest createPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = createPickupLocationValidateBeforeCall(createPickupLocationRequest, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<PickupLocationDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a pickup location (asynchronously)
     * 
     * @param createPickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Pickup location created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Code already exists </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createPickupLocationAsync(@javax.annotation.Nonnull CreatePickupLocationRequest createPickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<PickupLocationDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = createPickupLocationValidateBeforeCall(createPickupLocationRequest, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<PickupLocationDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deletePickupLocation
     * @param id Pickup location ID (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Pickup location deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePickupLocationCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/delivery/v1/pickup-locations/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deletePickupLocationValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deletePickupLocation(Async)");
        }

        return deletePickupLocationCall(id, acceptLanguage, _callback);

    }

    /**
     * Delete a pickup location
     * 
     * @param id Pickup location ID (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Pickup location deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public void deletePickupLocation(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        deletePickupLocationWithHttpInfo(id, acceptLanguage);
    }

    /**
     * Delete a pickup location
     * 
     * @param id Pickup location ID (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Pickup location deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deletePickupLocationWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = deletePickupLocationValidateBeforeCall(id, acceptLanguage, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete a pickup location (asynchronously)
     * 
     * @param id Pickup location ID (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Pickup location deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePickupLocationAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deletePickupLocationValidateBeforeCall(id, acceptLanguage, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPickupLocation
     * @param id Pickup location ID (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pickup location found </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPickupLocationCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/delivery/v1/pickup-locations/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPickupLocationValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getPickupLocation(Async)");
        }

        return getPickupLocationCall(id, acceptLanguage, _callback);

    }

    /**
     * Get a pickup location by ID
     * 
     * @param id Pickup location ID (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return PickupLocationDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pickup location found </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public PickupLocationDTO getPickupLocation(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<PickupLocationDTO> localVarResp = getPickupLocationWithHttpInfo(id, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Get a pickup location by ID
     * 
     * @param id Pickup location ID (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;PickupLocationDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pickup location found </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PickupLocationDTO> getPickupLocationWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = getPickupLocationValidateBeforeCall(id, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<PickupLocationDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a pickup location by ID (asynchronously)
     * 
     * @param id Pickup location ID (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pickup location found </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPickupLocationAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<PickupLocationDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPickupLocationValidateBeforeCall(id, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<PickupLocationDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for searchPickupLocations
     * @param searchPickupLocationsRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Search results returned </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call searchPickupLocationsCall(@javax.annotation.Nonnull SearchPickupLocationsRequest searchPickupLocationsRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = searchPickupLocationsRequest;

        // create path and map variables
        String localVarPath = "/delivery/v1/pickup-locations/search";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call searchPickupLocationsValidateBeforeCall(@javax.annotation.Nonnull SearchPickupLocationsRequest searchPickupLocationsRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'searchPickupLocationsRequest' is set
        if (searchPickupLocationsRequest == null) {
            throw new ApiException("Missing the required parameter 'searchPickupLocationsRequest' when calling searchPickupLocations(Async)");
        }

        return searchPickupLocationsCall(searchPickupLocationsRequest, acceptLanguage, _callback);

    }

    /**
     * Search pickup locations
     * 
     * @param searchPickupLocationsRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return PageResponseListPickupLocationDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Search results returned </td><td>  -  </td></tr>
     </table>
     */
    public PageResponseListPickupLocationDTO searchPickupLocations(@javax.annotation.Nonnull SearchPickupLocationsRequest searchPickupLocationsRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<PageResponseListPickupLocationDTO> localVarResp = searchPickupLocationsWithHttpInfo(searchPickupLocationsRequest, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Search pickup locations
     * 
     * @param searchPickupLocationsRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;PageResponseListPickupLocationDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Search results returned </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PageResponseListPickupLocationDTO> searchPickupLocationsWithHttpInfo(@javax.annotation.Nonnull SearchPickupLocationsRequest searchPickupLocationsRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = searchPickupLocationsValidateBeforeCall(searchPickupLocationsRequest, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<PageResponseListPickupLocationDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Search pickup locations (asynchronously)
     * 
     * @param searchPickupLocationsRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Search results returned </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call searchPickupLocationsAsync(@javax.annotation.Nonnull SearchPickupLocationsRequest searchPickupLocationsRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<PageResponseListPickupLocationDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = searchPickupLocationsValidateBeforeCall(searchPickupLocationsRequest, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<PageResponseListPickupLocationDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updatePickupLocation
     * @param id Pickup location ID (required)
     * @param updatePickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pickup location updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePickupLocationCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull UpdatePickupLocationRequest updatePickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updatePickupLocationRequest;

        // create path and map variables
        String localVarPath = "/delivery/v1/pickup-locations/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updatePickupLocationValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull UpdatePickupLocationRequest updatePickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updatePickupLocation(Async)");
        }

        // verify the required parameter 'updatePickupLocationRequest' is set
        if (updatePickupLocationRequest == null) {
            throw new ApiException("Missing the required parameter 'updatePickupLocationRequest' when calling updatePickupLocation(Async)");
        }

        return updatePickupLocationCall(id, updatePickupLocationRequest, acceptLanguage, _callback);

    }

    /**
     * Update a pickup location
     * 
     * @param id Pickup location ID (required)
     * @param updatePickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return PickupLocationDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pickup location updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public PickupLocationDTO updatePickupLocation(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull UpdatePickupLocationRequest updatePickupLocationRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<PickupLocationDTO> localVarResp = updatePickupLocationWithHttpInfo(id, updatePickupLocationRequest, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Update a pickup location
     * 
     * @param id Pickup location ID (required)
     * @param updatePickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;PickupLocationDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pickup location updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PickupLocationDTO> updatePickupLocationWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull UpdatePickupLocationRequest updatePickupLocationRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = updatePickupLocationValidateBeforeCall(id, updatePickupLocationRequest, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<PickupLocationDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a pickup location (asynchronously)
     * 
     * @param id Pickup location ID (required)
     * @param updatePickupLocationRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pickup location updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePickupLocationAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull UpdatePickupLocationRequest updatePickupLocationRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<PickupLocationDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = updatePickupLocationValidateBeforeCall(id, updatePickupLocationRequest, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<PickupLocationDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
