/*
 * Delivery Api Service
 * This API exposes endpoints.  ## Authentication  All API endpoints require a **Bearer JWT token** in the `Authorization` header.  Tokens are issued by the **Auth Service** via OAuth2 client credentials flow.  ### Obtain a token  ``` POST {auth-service-url}/oauth/token Authorization: Basic Base64(apiKey:apiSecret) Content-Type: application/x-www-form-urlencoded  grant_type=client_credentials ```  Credentials must be provided via **HTTP Basic Authentication** (Base64-encoded `apiKey:apiSecret`).  ### Use the token  ``` Authorization: Bearer {access_token} ```  > Contact your administrator to obtain API credentials (apiKey / apiSecret). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.api;

import com.zipper.delivery.hub.sdk.ApiCallback;
import com.zipper.delivery.hub.sdk.ApiClient;
import com.zipper.delivery.hub.sdk.ApiException;
import com.zipper.delivery.hub.sdk.ApiResponse;
import com.zipper.delivery.hub.sdk.Configuration;
import com.zipper.delivery.hub.sdk.Pair;
import com.zipper.delivery.hub.sdk.ProgressRequestBody;
import com.zipper.delivery.hub.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.delivery.hub.sdk.model.PublicTrackingResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PublicTrackingApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PublicTrackingApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PublicTrackingApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for track
     * @param trackingNumber Delivery tracking number (e.g. ZIPPERGUDWXJNXTTJ17) (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tracking information returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Delivery not found </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call trackCall(@javax.annotation.Nonnull String trackingNumber, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/delivery/v1/public/track/{trackingNumber}"
            .replace("{" + "trackingNumber" + "}", localVarApiClient.escapeString(trackingNumber.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call trackValidateBeforeCall(@javax.annotation.Nonnull String trackingNumber, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'trackingNumber' is set
        if (trackingNumber == null) {
            throw new ApiException("Missing the required parameter 'trackingNumber' when calling track(Async)");
        }

        return trackCall(trackingNumber, acceptLanguage, _callback);

    }

    /**
     * Track a delivery by tracking number
     * Returns public tracking information for a delivery. No authentication required.
     * @param trackingNumber Delivery tracking number (e.g. ZIPPERGUDWXJNXTTJ17) (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return PublicTrackingResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tracking information returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Delivery not found </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
     </table>
     */
    public PublicTrackingResponse track(@javax.annotation.Nonnull String trackingNumber, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<PublicTrackingResponse> localVarResp = trackWithHttpInfo(trackingNumber, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Track a delivery by tracking number
     * Returns public tracking information for a delivery. No authentication required.
     * @param trackingNumber Delivery tracking number (e.g. ZIPPERGUDWXJNXTTJ17) (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;PublicTrackingResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tracking information returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Delivery not found </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PublicTrackingResponse> trackWithHttpInfo(@javax.annotation.Nonnull String trackingNumber, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = trackValidateBeforeCall(trackingNumber, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<PublicTrackingResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Track a delivery by tracking number (asynchronously)
     * Returns public tracking information for a delivery. No authentication required.
     * @param trackingNumber Delivery tracking number (e.g. ZIPPERGUDWXJNXTTJ17) (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tracking information returned </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Delivery not found </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call trackAsync(@javax.annotation.Nonnull String trackingNumber, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<PublicTrackingResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = trackValidateBeforeCall(trackingNumber, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<PublicTrackingResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
